In [3]:
import math
import numpy as np
import pandas as pd

In [4]:
crashes = pd.read_csv('C:/Users/al797/Desktop/Crashes.csv')

In [5]:
people = pd.read_csv('C:/Users/al797/Desktop/People.csv')

In [6]:
vehicles = pd.read_csv('C:/Users/al797/Desktop/Vehicles.csv')

# CRASHES MISSING VALUES

In [13]:
crashes

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,JC113649,01/12/2019 12:01:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,0,7,1,41.894718,-87.716439,POINT (-87.716439109795 41.894718028422)
1,JC113627,01/11/2019 11:36:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,1,41.961558,-87.757564,POINT (-87.757564024038 41.961557797444)
2,JC113637,01/11/2019 11:31:00 PM,15,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,DARKNESS,SIDESWIPE OPPOSITE DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,1,41.791460,-87.715908,POINT (-87.715907858157 41.791459913725)
3,JC113630,01/11/2019 11:22:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,DARKNESS,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,23,6,1,41.876779,-87.741695,POINT (-87.741694507685 41.876778736117)
4,JC113604,01/11/2019 11:08:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,23,6,1,41.960921,-87.739893,POINT (-87.739893056441 41.960920858153)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257920,HY498942,11/11/2014 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,20,3,11,41.998270,-87.662997,POINT (-87.662996825424 41.998269693725)
257921,HZ400518,08/20/2014 04:50:00 PM,0,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,16,4,8,41.751143,-87.607091,POINT (-87.607090627909 41.751143217534)
257922,HZ164689,02/24/2014 07:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,19,2,2,41.884016,-87.701143,POINT (-87.701142757538 41.884016475152)
257923,HZ122950,01/21/2014 07:40:00 AM,30,YIELD,NO CONTROLS,CLEAR,DAYLIGHT,ANGLE,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,1.0,0.0,1.0,0.0,7,3,1,41.760710,-87.561946,POINT (-87.561946030143 41.760710194223)
257924,JB442550,01/18/2014 06:14:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DUSK,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,18,7,1,41.885610,-87.638756,POINT (-87.638756189808 41.885609917063)

In [70]:
p = people[people['PERSON_TYPE']=='BICYCLE']
pp = p[p['DRIVER_VISION'].isnull()]
pp

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
14567,O546123,BICYCLE,JB558408,NaN,12/18/2018 12:15:00 PM,NaN,NaN,F,NaN,USAGE UNKNOWN,NaN,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED,$500 OR LESS,NaN
23236,O537990,BICYCLE,JB544180,NaN,12/07/2018 07:45:00 AM,CHICAGO,IL,M,NaN,NaN,NaN,UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED,"OVER $1,500",3587.652066
28058,O532452,BICYCLE,JB534509,NaN,11/30/2018 11:20:00 AM,CHICAGO,IL,M,57.0,NONE PRESENT,NaN,NONE,"REPORTED, NOT EVIDENT",NONE,NaN,IMPAIRED - ALCOHOL,TEST NOT OFFERED,"$501 - $1,500",1399.748012
34529,O525841,BICYCLE,JB522622,NaN,11/20/2018 08:05:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED,$500 OR LESS,NaN
45087,O515108,BICYCLE,JB503567,NaN,11/04/2018 07:20:00 PM,CHICAGO,IL,M,32.0,NONE PRESENT,NaN,TOTALLY EJECTED,"REPORTED, NOT EVIDENT",IMPROPER LANE CHANGE,NaN,NORMAL,TEST NOT OFFERED,$500 OR LESS,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529938,O33876,BICYCLE,HZ185017,NaN,03/12/2016 09:10:00 PM,NaN,NaN,M,NaN,NaN,NaN,NaN,NO INDICATION OF INJURY,FOLLOWED TOO CLOSELY,NaN,NaN,TEST NOT OFFERED,$500 OR LESS,NaN
538659,O25687,BICYCLE,HZ132120,NaN,01/27/2016 03:00:00 PM,NaN,NaN,M,NaN,HELMET NOT USED,NaN,PARTIALLY EJECTED,NO INDICATION OF INJURY,FAILED TO YIELD,NaN,NaN,TEST NOT OFFERED,$500 OR LESS,NaN
539755,O24413,BICYCLE,HZ123704,NaN,01/21/2016 05:20:00 PM,NaN,NaN,NaN,NaN,NONE PRESENT,NaN,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED,"OVER $1,500",2105.581703
558819,O5708,BICYCLE,HY456928,NaN,10/10/2015 04:00:00 PM,CHICAGO,IL,M,28.0,NONE PRESENT,NaN,PARTIALLY EJECTED,NONINCAPACITATING INJURY,NaN,NaN,NaN,TEST NOT OFFERED,"$501 - $1,500",1188.917085
563205,O1285,BICYCLE,HY411973,NaN,09/05/2015 05:00:00 PM,NaN,NaN,M,NaN,USAGE UNKNOWN,NaN,TOTALLY EJECTED,NO INDICATION OF INJURY,UNKNOWN,NaN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",3654.752375

In [42]:
vehicles['MODEL'].value_counts()

MODEL
UNKNOWN                                           108204
CAMRY                                              16611
NISSAN ALTIMA                                      10153
COROLLA                                             9211
CIVIC                                               8529
                                                   ...
"FIBERFAB, INC. (MINNEAPOLIS, MINN.)"                  1
WILLIAMSEN TRUCK EQUIPMENT CORP.("WILLIAMSEN")         1
WAYFARER                                               1
ROLLS-ROYCE                                            1
Saloon (Virage), Virage (Saloon)                       1
Name: count, Length: 1574, dtype: int64

In [69]:
a = vehicles[vehicles['UNIT_TYPE'] == 'NON-CONTACT VEHICLE']
a['TRAVEL_DIRECTION'].value_counts()

DRIVER_VISION
NOT OBSCURED              257384
UNKNOWN                   176310
OTHER                       4091
MOVING VEHICLES             3015
PARKED VEHICLES             1624
WINDSHIELD (WATER/ICE)      1475
BLINDED - SUNLIGHT           549
TREES, PLANTS                193
BUILDINGS                    174
BLINDED - HEADLIGHTS          50
HILLCREST                     40
BLOWING MATERIALS             34
EMBANKMENT                    30
SIGNBOARD                     13
Name: count, dtype: int64

In [45]:
people['CITY'].value_counts()

CITY
CHICAGO           295710
CICERO              3988
SKOKIE              3026
EVANSTON            2586
BERWYN              2430
                   ...
CALUMETE CITY          1
NIAGARA FALLS          1
WHITNEY                1
MOINT PROSPECT         1
WYNNEWOOD              1
Name: count, Length: 6877, dtype: int64

In [48]:
vehicles['VEHICLE_YEAR'].value_counts()

VEHICLE_YEAR
2015.0    30888
2014.0    28576
2016.0    27549
2013.0    26273
2012.0    22816
          ...
2994.0        1
2203.0        1
2914.0        1
2402.0        1
1962.0        1
Name: count, Length: 131, dtype: int64

In [24]:
cc= crashes[crashes['BEAT_OF_OCCURRENCE'].isnull()]

cc

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
204846,HZ562684,12/23/2016 12:30:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,12,6,12,41.780148,-87.614552,POINT (-87.614552135332 41.780148264311)
206421,HZ552745,12/15/2016 03:10:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,15,5,12,41.786811,-87.653621,POINT (-87.653621088745 41.786811402722)
216083,HZ478865,10/17/2016 09:00:00 AM,30,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN,REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,9,2,10,NaN,NaN,NaN
216644,HZ472928,10/13/2016 03:40:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,15,5,10,41.994542,-87.713897,POINT (-87.713896783814 41.994542305274)

In [28]:
pp = crashes[crashes['LOCATION'] == 'POINT (-87.713896783814 41.994542305274)']
pp['BEAT_OF_OCCURRENCE']

71283     1711.0
80942     1711.0
112801    1711.0
138989    1711.0
152310    1711.0
216644       NaN
231923    1711.0
Name: BEAT_OF_OCCURRENCE, dtype: float64

In [ ]:
pp = crashes[crashes['LOCATION'] == 'POINT (-87.713896783814 41.994542305274)']
pp['BEAT_OF_OCCURRENCE']

In [ ]:
ccc = crashes[crashes[[]]]

In [74]:
crashes

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,JC113649,01/12/2019 12:01:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,0,7,1,41.894718,-87.716439,POINT (-87.716439109795 41.894718028422)
1,JC113627,01/11/2019 11:36:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,1,41.961558,-87.757564,POINT (-87.757564024038 41.961557797444)
2,JC113637,01/11/2019 11:31:00 PM,15,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,DARKNESS,SIDESWIPE OPPOSITE DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,1,41.791460,-87.715908,POINT (-87.715907858157 41.791459913725)
3,JC113630,01/11/2019 11:22:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,DARKNESS,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,23,6,1,41.876779,-87.741695,POINT (-87.741694507685 41.876778736117)
4,JC113604,01/11/2019 11:08:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,23,6,1,41.960921,-87.739893,POINT (-87.739893056441 41.960920858153)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257920,HY498942,11/11/2014 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,20,3,11,41.998270,-87.662997,POINT (-87.662996825424 41.998269693725)
257921,HZ400518,08/20/2014 04:50:00 PM,0,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,16,4,8,41.751143,-87.607091,POINT (-87.607090627909 41.751143217534)
257922,HZ164689,02/24/2014 07:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,19,2,2,41.884016,-87.701143,POINT (-87.701142757538 41.884016475152)
257923,HZ122950,01/21/2014 07:40:00 AM,30,YIELD,NO CONTROLS,CLEAR,DAYLIGHT,ANGLE,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,1.0,0.0,1.0,0.0,7,3,1,41.760710,-87.561946,POINT (-87.561946030143 41.760710194223)
257924,JB442550,01/18/2014 06:14:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DUSK,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,18,7,1,41.885610,-87.638756,POINT (-87.638756189808 41.885609917063)

Missing values:

REPORT_TYPE                      4996 X quelli con morti o feriti gravi vanno ON SCENE (circa 500), gli altri NOS

STREET_DIRECTION                    2  X quelle due strade hanno solo una direzione quindi top

STREET_NAME                         1  X NON ABBIAMO MODO DI TROVARLO, SI ELIMINA

BEAT_OF_OCCURRENCE                  4  X moda per le righe che hanno la stessa strada

MOST_SEVERE_INJURY                  7   X tutti 0 perche non si sono fatti nulla

LATITUDE                         1022   ? usare il coso di napo

LONGITUDE                        1022   ? usare il coso di napo

LOCATION                         1022   ? di conseguenza dopo longitude e latitude

In [67]:
most_sev = crashes[crashes['MOST_SEVERE_INJURY'].isnull()]
most_sev[['INJURIES_TOTAL', 'INJURIES_FATAL', 'INJURIES_INCAPACITATING', 'INJURIES_NON_INCAPACITATING', 'INJURIES_REPORTED_NOT_EVIDENT']]

,INJURIES_TOTAL,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT
14205,0.0,0.0,0.0,0.0,0.0
25482,0.0,0.0,0.0,0.0,0.0
146939,0.0,0.0,0.0,0.0,0.0
160254,0.0,0.0,0.0,0.0,0.0
185417,0.0,0.0,0.0,0.0,0.0
231203,0.0,0.0,0.0,0.0,0.0
243782,0.0,0.0,0.0,0.0,0.0

Siccome gli incidenti che hanno valori nulli in 'MOST_SEVERE_INJURY' non hanno feriti, possiamo dedurre che i feriti gravi siano 0 a loro volta.

In [79]:
crashes[crashes['REPORT_TYPE'].isnull()]

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
261,JC111906,01/10/2019 04:20:00 PM,30,STOP SIGN/FLASHER,NO CONTROLS,CLEAR,DUSK,ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,16,5,1,41.787206,-87.629228,POINT (-87.629227934408 41.787206312718)
340,JC111380,01/10/2019 08:25:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,8,5,1,41.880805,-87.630929,POINT (-87.630929332143 41.880805278204)
358,JC111967,01/10/2019 07:00:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",PEDESTRIAN,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,1.0,1.0,0.0,7,5,1,41.895544,-87.696641,POINT (-87.696641013859 41.895543709379)
465,JC110718,01/09/2019 03:15:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,PEDALCYCLIST,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,15,4,1,41.798255,-87.767411,POINT (-87.767410748126 41.798255116549)
543,JC110198,01/09/2019 09:30:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,9,4,1,42.012821,-87.670311,POINT (-87.670311474895 42.012821129153)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256278,HY437811,09/25/2015 12:05:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,FIXED OBJECT,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,12,6,9,41.943735,-87.671658,POINT (-87.671658301936 41.943735406008)
256417,HY433982,09/22/2015 04:40:00 PM,99,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,UNKNOWN,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,16,3,9,41.792219,-87.794082,POINT (-87.794082135983 41.792218535676)
257669,HY392560,08/21/2015 02:45:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,14,6,8,41.876664,-87.763321,POINT (-87.763321068783 41.876663779614)
257764,HY386254,08/15/2015 11:15:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,7,8,41.780521,-87.605869,POINT (-87.605869499248 41.780521024744)
257912,JB278951,05/25/2015 11:38:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",HEAD ON,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,2,5,41.877407,-87.745018,POINT (-87.745018287582 41.877406914781)

In [4]:
on_scene = crashes[crashes['REPORT_TYPE'] == 'ON SCENE']
on_scene

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,JC113649,01/12/2019 12:01:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,0,7,1,41.894718,-87.716439,POINT (-87.716439109795 41.894718028422)
1,JC113627,01/11/2019 11:36:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,1,41.961558,-87.757564,POINT (-87.757564024038 41.961557797444)
3,JC113630,01/11/2019 11:22:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,DARKNESS,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,23,6,1,41.876779,-87.741695,POINT (-87.741694507685 41.876778736117)
5,JC113579,01/11/2019 10:45:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,22,6,1,41.747016,-87.552951,POINT (-87.552951169307 41.74701568596)
6,JC113617,01/11/2019 10:28:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,22,6,1,41.954508,-87.747188,POINT (-87.747187880166 41.954508401874)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257615,HY394718,08/23/2015 06:40:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,18,1,8,41.881910,-87.645622,POINT (-87.645622201229 41.881909795065)
257735,HY386623,08/17/2015 05:45:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,17,2,8,41.889073,-87.774044,POINT (-87.774044359125 41.889073320855)
257830,HY376806,08/10/2015 12:48:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,12,2,8,41.911158,-87.627513,POINT (-87.627513305658 41.911157879859)
257876,HY372735,08/05/2015 02:30:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,14,4,8,41.865723,-87.705796,POINT (-87.705795692929 41.865722525805)
257923,HZ122950,01/21/2014 07:40:00 AM,30,YIELD,NO CONTROLS,CLEAR,DAYLIGHT,ANGLE,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,1.0,0.0,1.0,0.0,7,3,1,41.760710,-87.561946,POINT (-87.561946030143 41.760710194223)

In [31]:
crashes['LOCATION'].value_counts()

LOCATION
POINT (-87.905309125103 41.976201139024)    214
POINT (-87.585971992965 41.751460603167)    174
POINT (-87.580147768689 41.791420282098)    174
POINT (-87.585275565077 41.722257273006)    148
POINT (-87.741384758605 41.754660124394)    140
                                           ...
POINT (-87.777171644128 41.972823176085)      1
POINT (-87.664673909071 41.791774905754)      1
POINT (-87.673591580717 41.870513237197)      1
POINT (-87.697496431589 41.926739307023)      1
POINT (-87.607090627909 41.751143217534)      1
Name: count, Length: 132461, dtype: int64

In [5]:
crashes['MOST_SEVERE_INJURY'].value_counts()

MOST_SEVERE_INJURY
NO INDICATION OF INJURY     228475
NONINCAPACITATING INJURY     15808
REPORTED, NOT EVIDENT         9703
INCAPACITATING INJURY         3723
FATAL                          209
Name: count, dtype: int64

In [6]:
crashes['REPORT_TYPE'].value_counts()

REPORT_TYPE
NOT ON SCENE (DESK REPORT)    167961
ON SCENE                       84968
Name: count, dtype: int64

In [ ]:
vehicles[vehicles['VEHICLE_ID ']]

In [72]:
on_scene = crashes[crashes['REPORT_TYPE'] == 'ON SCENE']
on_scene = on_scene[on_scene['INJURIES_FATAL'] == 0]
on_scene = on_scene[on_scene['INJURIES_TOTAL'] == 0]


on_scene1 = on_scene[['CRASH_DATE','DATE_POLICE_NOTIFIED', 'INJURIES_FATAL', 'FIRST_CRASH_TYPE', 'CRASH_TYPE']]
on_scene1

,CRASH_DATE,DATE_POLICE_NOTIFIED,INJURIES_FATAL,FIRST_CRASH_TYPE,CRASH_TYPE
0,01/12/2019 12:01:00 AM,01/12/2019 12:01:00 AM,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY
1,01/11/2019 11:36:00 PM,01/11/2019 11:42:00 PM,0.0,ANGLE,INJURY AND / OR TOW DUE TO CRASH
3,01/11/2019 11:22:00 PM,01/11/2019 11:48:00 PM,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY
5,01/11/2019 10:45:00 PM,01/11/2019 10:45:00 PM,0.0,REAR END,NO INJURY / DRIVE AWAY
6,01/11/2019 10:28:00 PM,01/11/2019 10:28:00 PM,0.0,REAR END,INJURY AND / OR TOW DUE TO CRASH
...,...,...,...,...,...
257541,08/28/2015 07:40:00 AM,08/28/2015 07:40:00 AM,0.0,TURNING,NO INJURY / DRIVE AWAY
257615,08/23/2015 06:40:00 PM,08/23/2015 07:15:00 PM,0.0,TURNING,NO INJURY / DRIVE AWAY
257735,08/17/2015 05:45:00 PM,08/17/2015 06:47:00 PM,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY
257830,08/10/2015 12:48:00 PM,08/10/2015 03:40:00 PM,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY
257876,08/05/2015 02:30:00 PM,08/07/2015 01:00:00 PM,0.0,SIDESWIPE SAME DIRECTION,NO INJURY / DRIVE AWAY

In [78]:
piudueore = on_scene1[on_scene1['TIME_DIFFERENCE'] > pd.Timedelta(hours=2)]
piudueore

,CRASH_DATE,DATE_POLICE_NOTIFIED,INJURIES_FATAL,FIRST_CRASH_TYPE,CRASH_TYPE,TIME_DIFFERENCE
165,2019-01-11 06:00:00,2019-01-11 10:14:00,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY,0 days 04:14:00
170,2019-01-11 01:30:00,2019-01-11 19:44:00,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY,0 days 18:14:00
198,2019-01-10 20:00:00,2019-01-11 08:20:00,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY,0 days 12:20:00
212,2019-01-10 18:40:00,2019-01-10 21:16:00,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY,0 days 02:36:00
331,2019-01-10 08:50:00,2019-01-10 19:15:00,0.0,SIDESWIPE SAME DIRECTION,NO INJURY / DRIVE AWAY,0 days 10:25:00
...,...,...,...,...,...,...
256523,2015-09-21 07:30:00,2015-09-21 18:35:00,0.0,ANGLE,NO INJURY / DRIVE AWAY,0 days 11:05:00
256854,2015-09-16 10:30:00,2015-09-16 19:20:00,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY,0 days 08:50:00
257171,2015-09-08 19:00:00,2015-09-09 18:50:00,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY,0 days 23:50:00
257830,2015-08-10 12:48:00,2015-08-10 15:40:00,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY,0 days 02:52:00
257876,2015-08-05 14:30:00,2015-08-07 13:00:00,0.0,SIDESWIPE SAME DIRECTION,NO INJURY / DRIVE AWAY,1 days 22:30:00

In [73]:
# Convert columns to datetime format if they are not already
on_scene1['CRASH_DATE'] = pd.to_datetime(on_scene1['CRASH_DATE'])
on_scene1['DATE_POLICE_NOTIFIED'] = pd.to_datetime(on_scene1['DATE_POLICE_NOTIFIED'])

# Calculate the time difference
on_scene1['TIME_DIFFERENCE'] = on_scene1['DATE_POLICE_NOTIFIED'] - on_scene1['CRASH_DATE']

# Display the result
on_scene1[['CRASH_DATE', 'DATE_POLICE_NOTIFIED', 'TIME_DIFFERENCE']]

C:\Users\al797\AppData\Local\Temp\ipykernel_3940\2478064293.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  on_scene1['CRASH_DATE'] = pd.to_datetime(on_scene1['CRASH_DATE'])
C:\Users\al797\AppData\Local\Temp\ipykernel_3940\2478064293.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  on_scene1['CRASH_DATE'] = pd.to_datetime(on_scene1['CRASH_DATE'])
C:\Users\al797\AppData\Local\Temp\ipykernel_3940\2478064293.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  on_scene1['DATE_POLICE_NOTIFIED'] = pd.to_datetime(on_scene1['DATE_POLICE_NOTIFIED'])
C:\Users\al797\AppData\Local\Temp\ipykernel_3940\2478064293.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  on_scene1['DATE_POLICE_NOTIFIED'] = pd.to_datetime(on_scene1['DATE_POLICE_NOTIFIED'])
C:\Users\al797\AppData\Local\Temp\ipykernel_3940\2478064293.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  on_scene1['TIME_DIFFERENCE'] = on_scene1['DATE_POLICE_NOTIFIED'] - on_scene1['CRASH_DATE']

                CRASH_DATE DATE_POLICE_NOTIFIED TIME_DIFFERENCE
0      2019-01-12 00:01:00  2019-01-12 00:01:00 0 days 00:00:00
1      2019-01-11 23:36:00  2019-01-11 23:42:00 0 days 00:06:00
3      2019-01-11 23:22:00  2019-01-11 23:48:00 0 days 00:26:00
5      2019-01-11 22:45:00  2019-01-11 22:45:00 0 days 00:00:00
6      2019-01-11 22:28:00  2019-01-11 22:28:00 0 days 00:00:00
...                    ...                  ...             ...
257541 2015-08-28 07:40:00  2015-08-28 07:40:00 0 days 00:00:00
257615 2015-08-23 18:40:00  2015-08-23 19:15:00 0 days 00:35:00
257735 2015-08-17 17:45:00  2015-08-17 18:47:00 0 days 01:02:00
257830 2015-08-10 12:48:00  2015-08-10 15:40:00 0 days 02:52:00
257876 2015-08-05 14:30:00  2015-08-07 13:00:00 1 days 22:30:00

[63930 rows x 3 columns]

In [74]:
on_scene1_sorted = on_scene1.sort_values(by='TIME_DIFFERENCE', ascending=False)
on_scene1_sorted[['TIME_DIFFERENCE', 'CRASH_DATE', 'DATE_POLICE_NOTIFIED', 'CRASH_TYPE']]

,TIME_DIFFERENCE,CRASH_DATE,DATE_POLICE_NOTIFIED,CRASH_TYPE
247150,366 days 00:08:00,2016-01-11 22:50:00,2017-01-11 22:58:00,NO INJURY / DRIVE AWAY
117358,243 days 20:55:00,2018-01-09 11:05:00,2018-09-10 08:00:00,NO INJURY / DRIVE AWAY
200644,243 days 00:07:00,2017-01-22 20:30:00,2017-09-22 20:37:00,NO INJURY / DRIVE AWAY
117891,159 days 00:02:00,2018-01-07 06:57:00,2018-06-15 06:59:00,NO INJURY / DRIVE AWAY
116394,157 days 00:15:00,2018-01-12 12:30:00,2018-06-18 12:45:00,NO INJURY / DRIVE AWAY
...,...,...,...,...
137936,0 days 00:00:00,2017-11-06 02:04:00,2017-11-06 02:04:00,NO INJURY / DRIVE AWAY
24624,0 days 00:00:00,2018-10-22 19:29:00,2018-10-22 19:29:00,NO INJURY / DRIVE AWAY
174613,0 days 00:00:00,2017-06-23 17:33:00,2017-06-23 17:33:00,INJURY AND / OR TOW DUE TO CRASH
0,0 days 00:00:00,2019-01-12 00:01:00,2019-01-12 00:01:00,NO INJURY / DRIVE AWAY
98870,-1 days +23:03:00,2018-03-11 03:58:00,2018-03-11 03:01:00,INJURY AND / OR TOW DUE TO CRASH

In [86]:
on_scene_inj = crashes[crashes['REPORT_TYPE'] == 'ON SCENE']
on_scene_inj = on_scene_inj[on_scene_inj['INJURIES_FATAL'] > 0]

on_scene_inj = on_scene_inj[['CRASH_DATE','DATE_POLICE_NOTIFIED', 'INJURIES_FATAL', 'FIRST_CRASH_TYPE', 'CRASH_TYPE']]
on_scene_inj

,CRASH_DATE,DATE_POLICE_NOTIFIED,INJURIES_FATAL,FIRST_CRASH_TYPE,CRASH_TYPE
172,01/11/2019 01:09:00 AM,01/11/2019 01:09:00 AM,1.0,TURNING,INJURY AND / OR TOW DUE TO CRASH
918,01/07/2019 02:50:00 PM,01/07/2019 03:03:00 PM,1.0,PARKED MOTOR VEHICLE,INJURY AND / OR TOW DUE TO CRASH
1366,01/05/2019 03:25:00 PM,01/05/2019 03:28:00 PM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
4456,12/25/2018 07:05:00 PM,12/25/2018 07:06:00 PM,1.0,PARKED MOTOR VEHICLE,INJURY AND / OR TOW DUE TO CRASH
5063,12/22/2018 11:54:00 PM,12/22/2018 11:56:00 PM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
...,...,...,...,...,...
236298,05/08/2016 05:25:00 AM,05/08/2016 05:27:00 AM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
240994,03/19/2016 07:50:00 PM,03/19/2016 07:50:00 PM,1.0,ANGLE,INJURY AND / OR TOW DUE TO CRASH
249152,12/17/2015 08:49:00 AM,12/17/2015 08:49:00 AM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
252905,11/04/2015 07:25:00 AM,11/04/2015 07:28:00 AM,1.0,TURNING,INJURY AND / OR TOW DUE TO CRASH
253302,10/30/2015 03:01:00 PM,10/30/2015 03:01:00 PM,1.0,TURNING,INJURY AND / OR TOW DUE TO CRASH

In [9]:
crashes['REPORT_TYPE'].value_counts()

REPORT_TYPE
NOT ON SCENE (DESK REPORT)    167961
ON SCENE                       84968
Name: count, dtype: int64

In [87]:
on_scene_inj['CRASH_DATE'] = pd.to_datetime(on_scene_inj['CRASH_DATE'])
on_scene_inj['DATE_POLICE_NOTIFIED'] = pd.to_datetime(on_scene_inj['DATE_POLICE_NOTIFIED'])

on_scene_inj['TIME_DIFFERENCE'] = on_scene_inj['DATE_POLICE_NOTIFIED'] - on_scene_inj['CRASH_DATE']

on_scene_inj[['CRASH_DATE', 'DATE_POLICE_NOTIFIED', 'TIME_DIFFERENCE']]

                CRASH_DATE DATE_POLICE_NOTIFIED TIME_DIFFERENCE
172    2019-01-11 01:09:00  2019-01-11 01:09:00 0 days 00:00:00
918    2019-01-07 14:50:00  2019-01-07 15:03:00 0 days 00:13:00
1366   2019-01-05 15:25:00  2019-01-05 15:28:00 0 days 00:03:00
4456   2018-12-25 19:05:00  2018-12-25 19:06:00 0 days 00:01:00
5063   2018-12-22 23:54:00  2018-12-22 23:56:00 0 days 00:02:00
...                    ...                  ...             ...
236298 2016-05-08 05:25:00  2016-05-08 05:27:00 0 days 00:02:00
240994 2016-03-19 19:50:00  2016-03-19 19:50:00 0 days 00:00:00
249152 2015-12-17 08:49:00  2015-12-17 08:49:00 0 days 00:00:00
252905 2015-11-04 07:25:00  2015-11-04 07:28:00 0 days 00:03:00
253302 2015-10-30 15:01:00  2015-10-30 15:01:00 0 days 00:00:00

[162 rows x 3 columns]

In [88]:
on_scene_sorted = on_scene_inj.sort_values(by='TIME_DIFFERENCE', ascending=False)
on_scene_sorted[['TIME_DIFFERENCE', 'CRASH_DATE', 'DATE_POLICE_NOTIFIED', 'CRASH_TYPE']]

,TIME_DIFFERENCE,CRASH_DATE,DATE_POLICE_NOTIFIED,CRASH_TYPE
68092,0 days 02:22:00,2018-06-13 11:25:00,2018-06-13 13:47:00,INJURY AND / OR TOW DUE TO CRASH
79243,0 days 00:50:00,2018-05-12 02:30:00,2018-05-12 03:20:00,INJURY AND / OR TOW DUE TO CRASH
135776,0 days 00:37:00,2017-11-12 04:27:00,2017-11-12 05:04:00,INJURY AND / OR TOW DUE TO CRASH
52654,0 days 00:35:00,2018-07-28 23:30:00,2018-07-29 00:05:00,INJURY AND / OR TOW DUE TO CRASH
67858,0 days 00:29:00,2018-06-13 21:30:00,2018-06-13 21:59:00,INJURY AND / OR TOW DUE TO CRASH
...,...,...,...,...
107430,0 days 00:00:00,2018-02-11 17:07:00,2018-02-11 17:07:00,INJURY AND / OR TOW DUE TO CRASH
104508,0 days 00:00:00,2018-02-20 15:00:00,2018-02-20 15:00:00,INJURY AND / OR TOW DUE TO CRASH
100161,0 days 00:00:00,2018-03-07 00:08:00,2018-03-07 00:08:00,INJURY AND / OR TOW DUE TO CRASH
98864,0 days 00:00:00,2018-03-11 04:26:00,2018-03-11 04:26:00,INJURY AND / OR TOW DUE TO CRASH
253302,0 days 00:00:00,2015-10-30 15:01:00,2015-10-30 15:01:00,INJURY AND / OR TOW DUE TO CRASH

Gli incidenti ON SCENE che hanno una data DATE POLICE NOTIFIED successiva alla CRASH DATE sono incidenti:
1. non gravi ( 0 morti )
2. in cui CRASH TYPE è no injury / drive away

Gli incidenti ON SCENE che hanno almeno un morto, hanno chiamato la polizia entro 2 ore.

In [80]:
nulli = crashes[crashes['REPORT_TYPE'] == 'NOT ON SCENE (DESK REPORT)']

In [100]:
nulli_morti = nulli[(nulli['INJURIES_FATAL'] > 0) | (nulli['INJURIES_INCAPACITATING'] > 0)]
nulli_morti

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
1209,JC106607,01/06/2019 06:30:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,1.0,1.0,0.0,6,1,1,41.772992,-87.620214,POINT (-87.620214363055 41.772991929062)
1518,JC105985,01/04/2019 10:45:00 PM,30,NO CONTROLS,NO CONTROLS,SNOW,DARKNESS,PARKED MOTOR VEHICLE,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,22,6,1,41.883427,-87.766767,POINT (-87.766766694024 41.883426521819)
1977,JC103707,01/03/2019 12:25:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,FIXED OBJECT,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,12,5,1,41.802116,-87.621176,POINT (-87.621175709773 41.802115893337)
4380,JB567493,12/26/2018 08:50:00 AM,35,OTHER,UNKNOWN,CLEAR,DAYLIGHT,PEDESTRIAN,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,8,4,12,41.967884,-87.750543,POINT (-87.750542917889 41.967884257794)
4801,JB565653,12/24/2018 12:43:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,0,2,12,41.775064,-87.586091,POINT (-87.586090851669 41.775064310676)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255993,HY443811,09/30/2015 07:00:00 AM,25,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,7,4,9,41.852998,-87.622194,POINT (-87.622194479362 41.852997832724)
256384,HY435181,09/23/2015 11:30:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,11,4,9,41.885510,-87.728628,POINT (-87.728627542468 41.88550994044)
257239,HY424330,09/07/2015 02:51:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,14,2,9,41.998000,-87.667895,POINT (-87.667894531288 41.998000084956)
257318,HY414186,09/04/2015 11:10:00 PM,15,NO CONTROLS,NO CONTROLS,UNKNOWN,"DARKNESS, LIGHTED ROAD",PEDESTRIAN,PARKING LOT,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,9,41.764609,-87.683387,POINT (-87.683387053281 41.764608912236)
257862,HY372460,08/07/2015 09:00:00 AM,25,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,TURNING,OTHER,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,9,6,8,41.852991,-87.629387,POINT (-87.629386933044 41.852991219253)

questi sopra vanno messi ON SCENE, tutti gli altri NOT ON SCENE

In [100]:
not_on_scene = crashes[crashes['REPORT_TYPE'] == 'NOT ON SCENE (DESK REPORT)']
not_on_scene_inj = not_on_scene[not_on_scene['INJURIES_FATAL'] > 0]

not_on_scene_inj = not_on_scene_inj[['CRASH_DATE','DATE_POLICE_NOTIFIED', 'INJURIES_FATAL', 'FIRST_CRASH_TYPE', 'CRASH_TYPE']]
not_on_scene_inj

,CRASH_DATE,DATE_POLICE_NOTIFIED,INJURIES_FATAL,FIRST_CRASH_TYPE,CRASH_TYPE
1977,01/03/2019 12:25:00 PM,01/03/2019 12:59:00 PM,2.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
4801,12/24/2018 12:43:00 AM,12/24/2018 12:43:00 AM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
39990,09/06/2018 10:05:00 AM,09/06/2018 10:05:00 AM,1.0,REAR END,INJURY AND / OR TOW DUE TO CRASH
55199,07/20/2018 10:50:00 PM,07/20/2018 10:53:00 PM,1.0,PEDESTRIAN,INJURY AND / OR TOW DUE TO CRASH
142942,10/22/2017 02:13:00 AM,10/22/2017 02:15:00 AM,1.0,REAR END,INJURY AND / OR TOW DUE TO CRASH
159532,08/29/2017 05:56:00 AM,08/29/2017 06:00:00 AM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
175699,06/17/2017 11:47:00 PM,06/17/2017 11:47:00 PM,1.0,PEDESTRIAN,INJURY AND / OR TOW DUE TO CRASH
196443,02/21/2017 07:50:00 PM,02/22/2017 10:00:00 AM,1.0,PEDESTRIAN,INJURY AND / OR TOW DUE TO CRASH
212730,11/05/2016 01:33:00 PM,11/05/2016 02:40:00 PM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
218026,10/05/2016 05:20:00 AM,10/05/2016 05:20:00 AM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
226101,08/12/2016 11:35:00 PM,08/12/2016 11:37:00 PM,1.0,FIXED OBJECT,INJURY AND / OR TOW DUE TO CRASH
235129,05/20/2016 08:00:00 AM,05/20/2016 12:30:00 PM,1.0,TURNING,INJURY AND / OR TOW DUE TO CRASH
236411,05/06/2016 10:26:00 PM,05/06/2016 10:27:00 PM,1.0,SIDESWIPE SAME DIRECTION,INJURY AND / OR TOW DUE TO CRASH

In [87]:
not_on_scene = crashes[crashes['REPORT_TYPE'] == 'NOT ON SCENE (DESK REPORT)']
not_on_scene_totinj = not_on_scene[not_on_scene['INJURIES_INCAPACITATING'] > 0]
not_on_scene_totinj

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
1209,JC106607,01/06/2019 06:30:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,1.0,1.0,0.0,6,1,1,41.772992,-87.620214,POINT (-87.620214363055 41.772991929062)
1518,JC105985,01/04/2019 10:45:00 PM,30,NO CONTROLS,NO CONTROLS,SNOW,DARKNESS,PARKED MOTOR VEHICLE,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,22,6,1,41.883427,-87.766767,POINT (-87.766766694024 41.883426521819)
4380,JB567493,12/26/2018 08:50:00 AM,35,OTHER,UNKNOWN,CLEAR,DAYLIGHT,PEDESTRIAN,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,8,4,12,41.967884,-87.750543,POINT (-87.750542917889 41.967884257794)
5671,JB562159,12/21/2018 08:20:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDESTRIAN,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,8,6,12,41.752918,-87.683066,POINT (-87.683066415986 41.752917631271)
6024,JB560769,12/20/2018 09:00:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,FIXED OBJECT,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,9,5,12,41.670122,-87.559405,POINT (-87.559405015605 41.670121643392)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255993,HY443811,09/30/2015 07:00:00 AM,25,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,7,4,9,41.852998,-87.622194,POINT (-87.622194479362 41.852997832724)
256384,HY435181,09/23/2015 11:30:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,11,4,9,41.885510,-87.728628,POINT (-87.728627542468 41.88550994044)
257239,HY424330,09/07/2015 02:51:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,14,2,9,41.998000,-87.667895,POINT (-87.667894531288 41.998000084956)
257318,HY414186,09/04/2015 11:10:00 PM,15,NO CONTROLS,NO CONTROLS,UNKNOWN,"DARKNESS, LIGHTED ROAD",PEDESTRIAN,PARKING LOT,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,9,41.764609,-87.683387,POINT (-87.683387053281 41.764608912236)
257862,HY372460,08/07/2015 09:00:00 AM,25,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,TURNING,OTHER,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,9,6,8,41.852991,-87.629387,POINT (-87.629386933044 41.852991219253)

In [90]:
on_scene = crashes[crashes['REPORT_TYPE'] == 'ON SCENE']
on_scene_totinj = on_scene[on_scene['INJURIES_INCAPACITATING'] > 0]
on_scene_totinj

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
15,JC113432,01/11/2019 07:45:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,19,6,1,41.851850,-87.691272,POINT (-87.691271881535 41.851849723062)
160,JC112492,01/11/2019 07:00:00 AM,30,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,DAYLIGHT,HEAD ON,NOT DIVIDED,"CURVE, LEVEL",...,1.0,0.0,2.0,0.0,7,6,1,41.791143,-87.614785,POINT (-87.614785019318 41.791142972799)
172,JC112400,01/11/2019 01:09:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,0.0,0.0,4.0,0.0,1,6,1,41.886680,-87.630811,POINT (-87.630810638866 41.886680341851)
213,JC112093,01/10/2019 06:35:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PEDESTRIAN,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,18,5,1,41.943385,-87.644691,POINT (-87.644691338996 41.943385078619)
215,JC112121,01/10/2019 06:33:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,18,5,1,41.744030,-87.590761,POINT (-87.590761363724 41.744030464424)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255630,HY449907,10/05/2015 06:37:00 AM,30,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,6,2,10,41.895798,-87.692280,POINT (-87.692279730819 41.895797804651)
256061,HY442674,09/29/2015 08:47:00 AM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,ANGLE,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,8,3,9,41.884499,-87.648549,POINT (-87.648548758539 41.884498759292)
256128,HY441021,09/28/2015 12:05:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DUSK,ANGLE,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,1.0,0.0,0.0,0.0,0,2,9,41.765564,-87.624826,POINT (-87.624825828045 41.765563782008)
256665,HY428954,09/18/2015 08:41:00 PM,30,NO CONTROLS,NO CONTROLS,RAIN,DARKNESS,PEDESTRIAN,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,20,6,9,41.968230,-87.718990,POINT (-87.718990336631 41.968229611486)
256765,HY427241,09/17/2015 04:26:00 PM,40,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDESTRIAN,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,1.0,0.0,16,5,9,41.766191,-87.564770,POINT (-87.564770304214 41.766191214981)

In [103]:
not_on_scene = crashes[crashes['REPORT_TYPE'] == 'NOT ON SCENE (DESK REPORT)']
not_on_scene1 = not_on_scene[not_on_scene['INJURIES_FATAL'] == 0]

not_on_scene1 = not_on_scene1[['CRASH_DATE','DATE_POLICE_NOTIFIED', 'INJURIES_FATAL', 'FIRST_CRASH_TYPE', 'CRASH_TYPE']]
not_on_scene1

,CRASH_DATE,DATE_POLICE_NOTIFIED,INJURIES_FATAL,FIRST_CRASH_TYPE,CRASH_TYPE
2,01/11/2019 11:31:00 PM,01/12/2019 12:08:00 AM,0.0,SIDESWIPE OPPOSITE DIRECTION,NO INJURY / DRIVE AWAY
4,01/11/2019 11:08:00 PM,01/11/2019 11:38:00 PM,0.0,REAR END,NO INJURY / DRIVE AWAY
8,01/11/2019 10:00:00 PM,01/11/2019 10:30:00 PM,0.0,SIDESWIPE SAME DIRECTION,NO INJURY / DRIVE AWAY
10,01/11/2019 09:10:00 PM,01/11/2019 09:36:00 PM,0.0,REAR END,NO INJURY / DRIVE AWAY
13,01/11/2019 08:15:00 PM,01/11/2019 09:30:00 PM,0.0,SIDESWIPE SAME DIRECTION,NO INJURY / DRIVE AWAY
...,...,...,...,...,...
257919,01/10/2015 05:15:00 PM,01/10/2019 05:45:00 PM,0.0,REAR END,NO INJURY / DRIVE AWAY
257920,11/11/2014 08:00:00 PM,11/12/2015 02:40:00 PM,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY
257921,08/20/2014 04:50:00 PM,08/20/2016 08:32:00 PM,0.0,REAR END,NO INJURY / DRIVE AWAY
257922,02/24/2014 07:45:00 PM,02/25/2016 02:30:00 PM,0.0,TURNING,NO INJURY / DRIVE AWAY
257924,01/18/2014 06:14:00 PM,09/19/2018 07:00:00 PM,0.0,PARKED MOTOR VEHICLE,NO INJURY / DRIVE AWAY

In [104]:
not_on_scene_inj['CRASH_DATE'] = pd.to_datetime(not_on_scene_inj['CRASH_DATE'])
not_on_scene_inj['DATE_POLICE_NOTIFIED'] = pd.to_datetime(not_on_scene_inj['DATE_POLICE_NOTIFIED'])

not_on_scene_inj['TIME_DIFFERENCE'] = not_on_scene_inj['DATE_POLICE_NOTIFIED'] - not_on_scene_inj['CRASH_DATE']


not_on_scene_inj[['CRASH_DATE', 'DATE_POLICE_NOTIFIED', 'TIME_DIFFERENCE', 'CRASH_TYPE']]

,CRASH_DATE,DATE_POLICE_NOTIFIED,TIME_DIFFERENCE,CRASH_TYPE
1977,2019-01-03 12:25:00,2019-01-03 12:59:00,0 days 00:34:00,INJURY AND / OR TOW DUE TO CRASH
4801,2018-12-24 00:43:00,2018-12-24 00:43:00,0 days 00:00:00,INJURY AND / OR TOW DUE TO CRASH
39990,2018-09-06 10:05:00,2018-09-06 10:05:00,0 days 00:00:00,INJURY AND / OR TOW DUE TO CRASH
55199,2018-07-20 22:50:00,2018-07-20 22:53:00,0 days 00:03:00,INJURY AND / OR TOW DUE TO CRASH
142942,2017-10-22 02:13:00,2017-10-22 02:15:00,0 days 00:02:00,INJURY AND / OR TOW DUE TO CRASH
159532,2017-08-29 05:56:00,2017-08-29 06:00:00,0 days 00:04:00,INJURY AND / OR TOW DUE TO CRASH
175699,2017-06-17 23:47:00,2017-06-17 23:47:00,0 days 00:00:00,INJURY AND / OR TOW DUE TO CRASH
196443,2017-02-21 19:50:00,2017-02-22 10:00:00,0 days 14:10:00,INJURY AND / OR TOW DUE TO CRASH
212730,2016-11-05 13:33:00,2016-11-05 14:40:00,0 days 01:07:00,INJURY AND / OR TOW DUE TO CRASH
218026,2016-10-05 05:20:00,2016-10-05 05:20:00,0 days 00:00:00,INJURY AND / OR TOW DUE TO CRASH
226101,2016-08-12 23:35:00,2016-08-12 23:37:00,0 days 00:02:00,INJURY AND / OR TOW DUE TO CRASH
235129,2016-05-20 08:00:00,2016-05-20 12:30:00,0 days 04:30:00,INJURY AND / OR TOW DUE TO CRASH
236411,2016-05-06 22:26:00,2016-05-06 22:27:00,0 days 00:01:00,INJURY AND / OR TOW DUE TO CRASH

In [105]:
not_on_scene1['CRASH_DATE'] = pd.to_datetime(not_on_scene1['CRASH_DATE'])
not_on_scene1['DATE_POLICE_NOTIFIED'] = pd.to_datetime(not_on_scene1['DATE_POLICE_NOTIFIED'])

not_on_scene1['TIME_DIFFERENCE'] = not_on_scene1['DATE_POLICE_NOTIFIED'] - not_on_scene1['CRASH_DATE']


not_on_scene1[['CRASH_DATE', 'DATE_POLICE_NOTIFIED', 'TIME_DIFFERENCE', 'CRASH_TYPE']]

C:\Users\al797\AppData\Local\Temp\ipykernel_15216\4103441376.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  not_on_scene1['CRASH_DATE'] = pd.to_datetime(not_on_scene1['CRASH_DATE'])
C:\Users\al797\AppData\Local\Temp\ipykernel_15216\4103441376.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  not_on_scene1['DATE_POLICE_NOTIFIED'] = pd.to_datetime(not_on_scene1['DATE_POLICE_NOTIFIED'])

,CRASH_DATE,DATE_POLICE_NOTIFIED,TIME_DIFFERENCE,CRASH_TYPE
2,2019-01-11 23:31:00,2019-01-12 00:08:00,0 days 00:37:00,NO INJURY / DRIVE AWAY
4,2019-01-11 23:08:00,2019-01-11 23:38:00,0 days 00:30:00,NO INJURY / DRIVE AWAY
8,2019-01-11 22:00:00,2019-01-11 22:30:00,0 days 00:30:00,NO INJURY / DRIVE AWAY
10,2019-01-11 21:10:00,2019-01-11 21:36:00,0 days 00:26:00,NO INJURY / DRIVE AWAY
13,2019-01-11 20:15:00,2019-01-11 21:30:00,0 days 01:15:00,NO INJURY / DRIVE AWAY
...,...,...,...,...
257919,2015-01-10 17:15:00,2019-01-10 17:45:00,1461 days 00:30:00,NO INJURY / DRIVE AWAY
257920,2014-11-11 20:00:00,2015-11-12 14:40:00,365 days 18:40:00,NO INJURY / DRIVE AWAY
257921,2014-08-20 16:50:00,2016-08-20 20:32:00,731 days 03:42:00,NO INJURY / DRIVE AWAY
257922,2014-02-24 19:45:00,2016-02-25 14:30:00,730 days 18:45:00,NO INJURY / DRIVE AWAY
257924,2014-01-18 18:14:00,2018-09-19 19:00:00,1705 days 00:46:00,NO INJURY / DRIVE AWAY

Se in un dataset sugli incidenti stradali le colonne CRASH_DATE e DATE_POLICE_NOTIFIED coincidono (cioè indicano lo stesso momento) ma il REPORT_TYPE è indicato come "NOT ON SCENE", potrebbe significare che:

L'incidente è stato segnalato immediatamente: Anche se la polizia o un operatore non erano fisicamente sul luogo dell'incidente al momento della segnalazione, qualcuno ha notificato l'incidente alla stessa ora in cui è avvenuto (ad esempio, tramite telefono o sistema di notifica automatica).

Rapporto registrato in remoto: La segnalazione potrebbe essere stata fatta telefonicamente o online, con i dettagli dell'incidente riportati in tempo reale. Questo può accadere in situazioni in cui non è possibile inviare immediatamente qualcuno sul posto (ad esempio, incidenti minori o situazioni in cui non ci sono feriti gravi).

Sistema di registrazione automatizzato: In alcuni casi, soprattutto se ci sono tecnologie avanzate di rilevamento, come nei veicoli moderni dotati di sistemi di notifica automatica (come eCall in Europa), l'incidente può essere segnalato automaticamente alla stessa ora in cui si verifica, ma non viene considerato "on scene" poiché nessuno è fisicamente presente sul posto

In [19]:
crashes['REPORT_TYPE'].value_counts()

REPORT_TYPE
NOT ON SCENE (DESK REPORT)    167961
ON SCENE                       84968
Name: count, dtype: int64

In [46]:
people.head()

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
0,O561555,DRIVER,JC113649,535742.0,01/12/2019 12:01:00 AM,NaN,NaN,X,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,UNKNOWN,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",6069.089569
1,O561563,DRIVER,JC113627,535738.0,01/11/2019 11:36:00 PM,CHICAGO,IL,M,63.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",6237.638447
2,O561564,DRIVER,JC113627,535741.0,01/11/2019 11:36:00 PM,CHICAGO,IL,M,36.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,DISREGARDED CONTROL DEVICES,NOT OBSCURED,IMPAIRED - ALCOHOL,"TEST PERFORMED, RESULTS UNKNOWN","OVER $1,500",3802.304187
3,O561540,DRIVER,JC113637,535714.0,01/11/2019 11:31:00 PM,NaN,NaN,F,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,NONE,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",3127.680131
4,O561541,DRIVER,JC113637,535718.0,01/11/2019 11:31:00 PM,CHICAGO,IL,F,31.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",2225.886815

In [47]:
vehicles.head()

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
0,561555,JC113649,01/12/2019 12:01:00 AM,1,DRIVER,535742.0,UNKNOWN,UNKNOWN,XX,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,S,STRAIGHT AHEAD,1.0,REAR-RIGHT
1,561563,JC113627,01/11/2019 11:36:00 PM,2,DRIVER,535738.0,"TOYOTA MOTOR COMPANY, LTD.",Highlander(beginning vehicle year 2001),IL,2003.0,NONE,SPORT UTILITY VEHICLE (SUV),PERSONAL,S,STRAIGHT AHEAD,1.0,FRONT-RIGHT
2,561564,JC113627,01/11/2019 11:36:00 PM,1,DRIVER,535741.0,FORD,EXPLORER,IL,2001.0,NONE,SPORT UTILITY VEHICLE (SUV),PERSONAL,E,STRAIGHT AHEAD,1.0,FRONT-LEFT
3,561540,JC113637,01/11/2019 11:31:00 PM,1,DRIVER,535714.0,CHEVROLET,MALIBU (CHEVELLE),IL,2013.0,NONE,PASSENGER,PERSONAL,N,STRAIGHT AHEAD,1.0,SIDE-LEFT
4,561541,JC113637,01/11/2019 11:31:00 PM,2,DRIVER,535718.0,JEEP,LAREDO,IL,2016.0,NONE,PASSENGER,PERSONAL,S,STRAIGHT AHEAD,1.0,SIDE-LEFT

In [50]:
print('crashes null values:')
crashes.isnull().sum()

crashes null values:

RD_NO                               0
CRASH_DATE                          0
POSTED_SPEED_LIMIT                  0
TRAFFIC_CONTROL_DEVICE              0
DEVICE_CONDITION                    0
WEATHER_CONDITION                   0
LIGHTING_CONDITION                  0
FIRST_CRASH_TYPE                    0
TRAFFICWAY_TYPE                     0
ALIGNMENT                           0
ROADWAY_SURFACE_COND                0
ROAD_DEFECT                         0
REPORT_TYPE                      4996
CRASH_TYPE                          0
DATE_POLICE_NOTIFIED                0
PRIM_CONTRIBUTORY_CAUSE             0
SEC_CONTRIBUTORY_CAUSE              0
STREET_NO                           0
STREET_DIRECTION                    2
STREET_NAME                         1
BEAT_OF_OCCURRENCE                  4
NUM_UNITS                           0
MOST_SEVERE_INJURY                  7
INJURIES_TOTAL                      0
INJURIES_FATAL                      0
INJURIES_INCAPACITATING             0
INJURIES_NON_INCAPACITATING         0
INJURIES_REPORTED_NOT_EVIDENT       0
INJURIES_NO_INDICATION              0
INJURIES_UNKNOWN                    0
CRASH_HOUR                          0
CRASH_DAY_OF_WEEK                   0
CRASH_MONTH                         0
LATITUDE                         1022
LONGITUDE                        1022
LOCATION                         1022
dtype: int64

In [51]:
print('people null values:')
people.isnull().sum()

people null values:

PERSON_ID                     0
PERSON_TYPE                   0
RD_NO                         0
VEHICLE_ID                10696
CRASH_DATE                    0
CITY                     143920
STATE                    141976
SEX                        7154
AGE                      160981
SAFETY_EQUIPMENT           1410
AIRBAG_DEPLOYED           10452
EJECTION                   6705
INJURY_CLASSIFICATION       296
DRIVER_ACTION            109766
DRIVER_VISION            109884
PHYSICAL_CONDITION       109501
BAC_RESULT               108833
DAMAGE_CATEGORY               0
DAMAGE                    74309
dtype: int64

In [52]:
print('vehicles null values:')
vehicles.isnull().sum()

vehicles null values:

CRASH_UNIT_ID              0
RD_NO                      0
CRASH_DATE                 0
UNIT_NO                    0
UNIT_TYPE                  1
VEHICLE_ID             10373
MAKE                   10373
MODEL                  11786
LIC_PLATE_STATE        49629
VEHICLE_YEAR           88655
VEHICLE_DEFECT         10373
VEHICLE_TYPE           10373
VEHICLE_USE            10373
TRAVEL_DIRECTION       10373
MANEUVER               10373
OCCUPANT_CNT           10373
FIRST_CONTACT_POINT    10388
dtype: int64

In [53]:
crashes.columns

Index(['RD_NO', 'CRASH_DATE', 'POSTED_SPEED_LIMIT', 'TRAFFIC_CONTROL_DEVICE',
       'DEVICE_CONDITION', 'WEATHER_CONDITION', 'LIGHTING_CONDITION',
       'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE', 'ALIGNMENT',
       'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'REPORT_TYPE', 'CRASH_TYPE',
       'DATE_POLICE_NOTIFIED', 'PRIM_CONTRIBUTORY_CAUSE',
       'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO', 'STREET_DIRECTION',
       'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'NUM_UNITS', 'MOST_SEVERE_INJURY',
       'INJURIES_TOTAL', 'INJURIES_FATAL', 'INJURIES_INCAPACITATING',
       'INJURIES_NON_INCAPACITATING', 'INJURIES_REPORTED_NOT_EVIDENT',
       'INJURIES_NO_INDICATION', 'INJURIES_UNKNOWN', 'CRASH_HOUR',
       'CRASH_DAY_OF_WEEK', 'CRASH_MONTH', 'LATITUDE', 'LONGITUDE',
       'LOCATION'],
      dtype='object')

In [54]:
people.columns

Index(['PERSON_ID', 'PERSON_TYPE', 'RD_NO', 'VEHICLE_ID', 'CRASH_DATE', 'CITY',
       'STATE', 'SEX', 'AGE', 'SAFETY_EQUIPMENT', 'AIRBAG_DEPLOYED',
       'EJECTION', 'INJURY_CLASSIFICATION', 'DRIVER_ACTION', 'DRIVER_VISION',
       'PHYSICAL_CONDITION', 'BAC_RESULT', 'DAMAGE_CATEGORY', 'DAMAGE'],
      dtype='object')

In [55]:
vehicles.columns

Index(['CRASH_UNIT_ID', 'RD_NO', 'CRASH_DATE', 'UNIT_NO', 'UNIT_TYPE',
       'VEHICLE_ID', 'MAKE', 'MODEL', 'LIC_PLATE_STATE', 'VEHICLE_YEAR',
       'VEHICLE_DEFECT', 'VEHICLE_TYPE', 'VEHICLE_USE', 'TRAVEL_DIRECTION',
       'MANEUVER', 'OCCUPANT_CNT', 'FIRST_CONTACT_POINT'],
      dtype='object')

In [20]:
new_df = crashes[crashes['REPORT_TYPE'].isnull()]
new_df

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
261,JC111906,01/10/2019 04:20:00 PM,30,STOP SIGN/FLASHER,NO CONTROLS,CLEAR,DUSK,ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,16,5,1,41.787206,-87.629228,POINT (-87.629227934408 41.787206312718)
340,JC111380,01/10/2019 08:25:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,8,5,1,41.880805,-87.630929,POINT (-87.630929332143 41.880805278204)
358,JC111967,01/10/2019 07:00:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",PEDESTRIAN,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,1.0,1.0,0.0,7,5,1,41.895544,-87.696641,POINT (-87.696641013859 41.895543709379)
465,JC110718,01/09/2019 03:15:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,PEDALCYCLIST,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,15,4,1,41.798255,-87.767411,POINT (-87.767410748126 41.798255116549)
543,JC110198,01/09/2019 09:30:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,9,4,1,42.012821,-87.670311,POINT (-87.670311474895 42.012821129153)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256278,HY437811,09/25/2015 12:05:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,FIXED OBJECT,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,12,6,9,41.943735,-87.671658,POINT (-87.671658301936 41.943735406008)
256417,HY433982,09/22/2015 04:40:00 PM,99,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,UNKNOWN,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,16,3,9,41.792219,-87.794082,POINT (-87.794082135983 41.792218535676)
257669,HY392560,08/21/2015 02:45:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,14,6,8,41.876664,-87.763321,POINT (-87.763321068783 41.876663779614)
257764,HY386254,08/15/2015 11:15:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,7,8,41.780521,-87.605869,POINT (-87.605869499248 41.780521024744)
257912,JB278951,05/25/2015 11:38:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",HEAD ON,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,2,5,41.877407,-87.745018,POINT (-87.745018287582 41.877406914781)

In [30]:
new_df.groupby(['RD_NO'])

In [8]:
for col in crashes.columns:
    print(f"Colonna {col}:")
    print(crashes[col].unique())

Colonna RD_NO:
['JC113649' 'JC113627' 'JC113637' ... 'HZ164689' 'HZ122950' 'JB442550']
Colonna CRASH_DATE:
['01/12/2019 12:01:00 AM' '01/11/2019 11:36:00 PM'
 '01/11/2019 11:31:00 PM' ... '02/24/2014 07:45:00 PM'
 '01/21/2014 07:40:00 AM' '01/18/2014 06:14:00 PM']
Colonna POSTED_SPEED_LIMIT:
[30 15 35 40  5 25 10 20  0 45  3 39 55  1 60 70 50  2 22  9 24 14  7 33
 32 36 65 23 34  4 26  6 63 18 12 38 99]
Colonna TRAFFIC_CONTROL_DEVICE:
['NO CONTROLS' 'STOP SIGN/FLASHER' 'TRAFFIC SIGNAL' 'OTHER' 'UNKNOWN'
 'LANE USE MARKING' 'OTHER REG. SIGN' 'POLICE/FLAGMAN'
 'OTHER WARNING SIGN' 'RAILROAD CROSSING GATE' 'YIELD' 'DELINEATORS'
 'SCHOOL ZONE' 'OTHER RAILROAD CROSSING' 'NO PASSING']
Colonna DEVICE_CONDITION:
['NO CONTROLS' 'FUNCTIONING PROPERLY' 'OTHER' 'UNKNOWN'
 'FUNCTIONING IMPROPERLY' 'NOT FUNCTIONING' 'WORN REFLECTIVE MATERIAL'
 'MISSING']
Colonna WEATHER_CONDITION:
['CLEAR' 'CLOUDY/OVERCAST' 'UNKNOWN' 'SNOW' 'RAIN' 'OTHER'
 'SEVERE CROSS WIND GATE' 'FOG/SMOKE/HAZE' 'SLEET/HAIL']
Colonna LIGHTING_CONDITION:
['DARKNESS, LIGHTED ROAD' 'DARKNESS' 'DUSK' 'DAYLIGHT' 'UNKNOWN' 'DAWN']
Colonna FIRST_CRASH_TYPE:
['PARKED MOTOR VEHICLE' 'ANGLE' 'SIDESWIPE OPPOSITE DIRECTION' 'REAR END'
 'SIDESWIPE SAME DIRECTION' 'TURNING' 'PEDESTRIAN' 'FIXED OBJECT'
 'PEDALCYCLIST' 'HEAD ON' 'OTHER OBJECT' 'ANIMAL' 'OTHER NONCOLLISION'
 'OVERTURNED' 'TRAIN']
Colonna TRAFFICWAY_TYPE:
['NOT DIVIDED' 'DIVIDED - W/MEDIAN (NOT RAISED)' 'OTHER' 'PARKING LOT'
 'ONE-WAY' 'ALLEY' 'CENTER TURN LANE' 'DIVIDED - W/MEDIAN BARRIER' 'RAMP'
 'DRIVEWAY' 'UNKNOWN']
Colonna ALIGNMENT:
['STRAIGHT AND LEVEL' 'CURVE, LEVEL' 'STRAIGHT ON GRADE'
 'STRAIGHT ON HILLCREST' 'CURVE ON GRADE' 'CURVE ON HILLCREST']
Colonna ROADWAY_SURFACE_COND:
['DRY' 'WET' 'UNKNOWN' 'SNOW OR SLUSH' 'ICE' 'OTHER' 'SAND, MUD, DIRT']
Colonna ROAD_DEFECT:
['NO DEFECTS' 'UNKNOWN' 'WORN SURFACE' 'RUT, HOLES' 'DEBRIS ON ROADWAY'
 'OTHER' 'SHOULDER DEFECT']
Colonna REPORT_TYPE:
['ON SCENE' 'NOT ON SCENE (DESK REPORT)' nan]
Colonna CRASH_TYPE:
['NO INJURY / DRIVE AWAY' 'INJURY AND / OR TOW DUE TO CRASH']
Colonna DATE_POLICE_NOTIFIED:
['01/12/2019 12:01:00 AM' '01/11/2019 11:42:00 PM'
 '01/12/2019 12:08:00 AM' ... '08/20/2016 08:32:00 PM'
 '02/25/2016 02:30:00 PM' '01/21/2016 07:50:00 AM']
Colonna PRIM_CONTRIBUTORY_CAUSE:
['UNABLE TO DETERMINE'
 'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)'
 'IMPROPER LANE USAGE' 'IMPROPER OVERTAKING/PASSING'
 'FOLLOWING TOO CLOSELY' 'EXCEEDING AUTHORIZED SPEED LIMIT'
 'EQUIPMENT - VEHICLE CONDITION' 'IMPROPER TURNING/NO SIGNAL'
 'FAILING TO YIELD RIGHT-OF-WAY' 'IMPROPER BACKING' 'NOT APPLICABLE'
 'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER'
 'DISREGARDING TRAFFIC SIGNALS' 'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE'
 'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)'
 'FAILING TO REDUCE SPEED TO AVOID CRASH' 'ROAD CONSTRUCTION/MAINTENANCE'
 'EXCEEDING SAFE SPEED FOR CONDITIONS'
 'DISTRACTION - FROM OUTSIDE VEHICLE'
 'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST'
 'DRIVING ON WRONG SIDE/WRONG WAY'
 'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)'
 'DISREGARDING STOP SIGN' 'ROAD ENGINEERING/SURFACE/MARKING DEFECTS'
 'DISTRACTION - FROM INSIDE VEHICLE' 'WEATHER' 'ANIMAL'
 'PHYSICAL CONDITION OF DRIVER' 'TURNING RIGHT ON RED'
 'DISREGARDING YIELD SIGN' 'CELL PHONE USE OTHER THAN TEXTING'
 'DISREGARDING OTHER TRAFFIC SIGNS'
 'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)'
 'DISREGARDING ROAD MARKINGS' 'TEXTING' 'PASSING STOPPED SCHOOL BUS'
 'BICYCLE ADVANCING LEGALLY ON RED LIGHT'
 'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT']
Colonna SEC_CONTRIBUTORY_CAUSE:
['UNABLE TO DETERMINE' 'DISREGARDING STOP SIGN' 'NOT APPLICABLE'
 'FAILING TO REDUCE SPEED TO AVOID CRASH' 'EQUIPMENT - VEHICLE CONDITION'
 'FOLLOWING TOO CLOSELY' 'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE'
 'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)'
 'IMPROPER LANE USAGE' 'FAILING TO YIELD RIGHT-OF-WAY'
 'DRIVING ON WRONG SIDE/WRONG WAY' 'IMPROPER TURNING/NO SIGNAL'
 'IMPROPER OVERTAKING/PASSING' 'IMPROPER BACKING'
 'ROAD CONSTRUCTION/MAINTENANCE' 'DISREGARDING TRAFFIC SIGNALS'
 'EXCEEDING AUTHORIZED SPEED LIMIT' 'DISTRACTION - FROM OUTSIDE VEHICLE'
 'EXCEEDING SAFE SPEED FOR CONDITIONS' 'DISREGARDING ROAD MARKINGS'
 'DISTRACTION - FROM INSIDE VEHICLE' 'CELL PHONE USE OTHER THAN TEXTING'
 'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER'
 'HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)' 'WEATHER'
 'MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT'
 'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)'
 'BICYCLE ADVANCING LEGALLY ON RED LIGHT'
 'DISREGARDING OTHER TRAFFIC SIGNS'
 'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)'
 'TEXTING' 'ANIMAL' 'PHYSICAL CONDITION OF DRIVER'
 'DISREGARDING YIELD SIGN' 'ROAD ENGINEERING/SURFACE/MARKING DEFECTS'
 'TURNING RIGHT ON RED'
 'EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST'
 'PASSING STOPPED SCHOOL BUS']
Colonna STREET_NO:
[  734  4432  5600 ... 10821  9827  6167]
Colonna STREET_DIRECTION:
['N' 'S' 'W' 'E' nan]
Colonna STREET_NAME:
['CENTRAL PARK AVE' 'LARAMIE AVE' 'LAWNDALE AVE' ... 'KEENE AVE'
 'FRANKLIN SD' 'KINZIE']
Colonna BEAT_OF_OCCURRENCE:
[1112. 1623.  822. 1131. 1722.  422.  334.  412. 2223. 1712. 1621.  815.
 1622. 1034. 1223. 1023. 2523.  813. 1932. 2532. 1724. 2512. 1121.  312.
 1231.  921. 1222. 1813. 1033.  633.  332.  726.  133.  532. 1922. 1822.
 1723. 2521.  725. 2411.  114.  631. 2514. 1135.  724.  713. 2432. 1434.
 2423. 1022. 1235. 1421.  124. 1413.  122. 1533.  731.  832.  331.  612.
  734. 1921. 1224. 1632. 2213. 1221.  623. 1733. 2221.  911. 1122.  632.
  811.  413. 1614. 1133.  722. 2013. 1232. 2533. 1011. 1212.  523. 2534.
  322. 1811. 1432. 2412. 1831.  931. 2032. 1013.  423. 2031. 1225.  432.
 1935.  924. 1933.  614. 2222.  914.  224. 2413. 1934. 1424. 1834. 1731.
  211.  414. 1233.  434. 2232.  935.  112.  823.  831. 1031. 1123.  233.
  922.  113. 1113.  834.  123. 1433. 1651.  111.  833. 1633. 2022. 1523.
 1234. 1913. 2211. 1832. 1611.  132.  824. 1925.  923. 1111. 1711. 1631.
 2023.  913.  915.  513.  131. 1132. 1522. 1833.  235.  411.  222. 2515.
  232. 2012. 1624. 1513.  121. 2011.  912. 1821. 2212. 1812. 1612. 2234.
  225. 1713. 1911. 1814.  814.  511. 2513.  221. 1654. 1422.  314. 1732.
 1931. 1915. 1411. 2233. 1214.  812. 1114. 1824.  622. 1923. 1823.  932.
  212. 2433.  512. 1115.  311.  624. 1211. 2525. 2511. 1431. 1032.  934.
 1213.  835. 2424.  621.  735.  732. 1014. 2024.  234. 1012. 1215.  431.
 2524.  424. 1613.  421.  712.  333. 1414. 2535. 1531.  634. 1912.  321.
  231. 2422. 1524.  611.  433. 1412.  323. 1124.  711. 2522.  324. 1634.
  825. 1924.  213.  821.  524. 2531. 1511.  933.  925. 2431.  215. 1532.
 2033.  715.  613. 1125. 1024. 1423. 1914. 1512.  714.  214.  223.  531.
  723.  533. 1021.  733. 1134.  522.  313. 1653. 1655. 1652.   nan]
Colonna NUM_UNITS:
[ 6.  2.  3.  4.  1.  7.  5.  8. 12.  9. 10. 16. 18. 11.]
Colonna MOST_SEVERE_INJURY:
['NO INDICATION OF INJURY' 'NONINCAPACITATING INJURY'
 'INCAPACITATING INJURY' 'REPORTED, NOT EVIDENT' 'FATAL' nan]
Colonna INJURIES_TOTAL:
[ 0.  1.  2.  3.  4.  5.  7.  8.  6.  9. 21. 10. 11. 13.]
Colonna INJURIES_FATAL:
[0. 1. 2. 3.]
Colonna INJURIES_INCAPACITATING:
[0. 1. 2. 3. 4. 5. 7. 6.]
Colonna INJURIES_NON_INCAPACITATING:
[ 0.  1.  2.  3.  6.  4.  5.  8. 21.  7. 11. 10.  9.]
Colonna INJURIES_REPORTED_NOT_EVIDENT:
[ 0.  1.  3.  2.  5.  4.  7. 10.  6.  9.  8.]
Colonna INJURIES_NO_INDICATION:
[ 1.  2.  3.  4.  0.  5.  8.  6. 17.  7. 11. 12.  9. 18. 14. 22. 13. 10.
 20. 21. 16. 29. 19. 31. 40. 27. 15. 42. 30. 26. 37. 45. 34. 36. 61. 25.
 33. 39. 28. 38.]
Colonna INJURIES_UNKNOWN:
[0.]
Colonna CRASH_HOUR:
[ 0 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  1  3  2]
Colonna CRASH_DAY_OF_WEEK:
[7 6 5 4 3 2 1]
Colonna CRASH_MONTH:
[ 1 12 11 10  9  8  7  6  5  4  3  2]
Colonna LATITUDE:
[41.89471803 41.9615578  41.79145991 ... 41.81271141 41.99826969
 41.75114322]
Colonna LONGITUDE:
[-87.71643911 -87.75756402 -87.71590786 ... -87.66522212 -87.66299682
 -87.60709063]
Colonna LOCATION:
['POINT (-87.716439109795 41.894718028422)'
 'POINT (-87.757564024038 41.961557797444)'
 'POINT (-87.715907858157 41.791459913725)' ...
 'POINT (-87.665222121664 41.812711404865)'
 'POINT (-87.662996825424 41.998269693725)'
 'POINT (-87.607090627909 41.751143217534)']

In [11]:
import pandas as pd

# Esempio di DataFrame
# df = pd.DataFrame({'LATITUDE': [...], 'LONGITUDE': [...], 'LOCATION': [...]})

# Crea una maschera booleana per i valori mancanti
missing_latitude = crashes['LATITUDE'].isnull()
missing_longitude = crashes['LONGITUDE'].isnull()
missing_location = crashes['LOCATION'].isnull()

# Crea un DataFrame per mostrare le righe con missing values
missing_df = pd.DataFrame({
    'LATITUDE': missing_latitude,
    'LONGITUDE': missing_longitude,
    'LOCATION': missing_location
})

# Verifica se le righe con missing values corrispondono
missing_rows = missing_df.all(axis=1)

# Stampa le righe che hanno missing values in tutte e tre le colonne
result = crashes[missing_rows]
print(result)

           RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
362     JC111300  01/10/2019 06:45:00 AM                  30
434     JC110810  01/09/2019 05:30:00 PM                  25
893     JC108234  01/07/2019 04:00:00 PM                  30
1322    JC106096  01/05/2019 05:40:00 PM                  30
1586    JC104707  01/04/2019 05:02:00 PM                  30
...          ...                     ...                 ...
257407  HY415107  09/02/2015 12:00:00 PM                  30
257568  HY397975  08/26/2015 11:00:00 AM                  30
257751  HY385753  08/17/2015 08:20:00 AM                  30
257831  HY376488  08/10/2015 09:15:00 AM                  30
257847  HY374513  08/08/2015 04:35:00 PM                  35

       TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
362            TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR
434               NO CONTROLS           NO CONTROLS             CLEAR
893               NO CONTROLS           NO CONTROLS              RAIN
1322           TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR
1586              NO CONTROLS           NO CONTROLS             CLEAR
...                       ...                   ...               ...
257407            NO CONTROLS           NO CONTROLS             CLEAR
257568            NO CONTROLS           NO CONTROLS             CLEAR
257751         TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR
257831         TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR
257847            NO CONTROLS           NO CONTROLS             CLEAR

            LIGHTING_CONDITION          FIRST_CRASH_TYPE  \
362                   DAYLIGHT  SIDESWIPE SAME DIRECTION
434                   DARKNESS  SIDESWIPE SAME DIRECTION
893     DARKNESS, LIGHTED ROAD                   TURNING
1322    DARKNESS, LIGHTED ROAD                   TURNING
1586    DARKNESS, LIGHTED ROAD                  REAR END
...                        ...                       ...
257407  DARKNESS, LIGHTED ROAD      PARKED MOTOR VEHICLE
257568                DAYLIGHT                  REAR END
257751                DAYLIGHT  SIDESWIPE SAME DIRECTION
257831                DAYLIGHT                   TURNING
257847                DAYLIGHT                  REAR END

                        TRAFFICWAY_TYPE           ALIGNMENT  ...  \
362                         NOT DIVIDED  STRAIGHT AND LEVEL  ...
434                                RAMP  STRAIGHT AND LEVEL  ...
893     DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...
1322                            ONE-WAY  STRAIGHT AND LEVEL  ...
1586                        NOT DIVIDED  STRAIGHT AND LEVEL  ...
...                                 ...                 ...  ...
257407                      NOT DIVIDED  STRAIGHT AND LEVEL  ...
257568                          ONE-WAY  STRAIGHT AND LEVEL  ...
257751                      NOT DIVIDED  STRAIGHT AND LEVEL  ...
257831  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...
257847                          ONE-WAY  STRAIGHT AND LEVEL  ...

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
362                            0.0                           0.0
434                            0.0                           0.0
893                            0.0                           0.0
1322                           0.0                           0.0
1586                           0.0                           0.0
...                            ...                           ...
257407                         0.0                           0.0
257568                         0.0                           0.0
257751                         0.0                           0.0
257831                         0.0                           0.0
257847                         0.0                           0.0

       INJURIES_NO_INDICATION INJURIES_UNKNOWN CRASH_HOUR CRASH_DAY_OF_WEEK  \
362                       2.0              0.0          6                 5
434                       2.0              0.0         17                 4
893                       2.0              0.0         16                 2
1322                      2.0              0.0         17                 7
1586                      3.0              0.0         17                 6
...                       ...              ...        ...               ...
257407                    1.0              0.0         12                 4
257568                    2.0              0.0         11                 4
257751                    2.0              0.0          8                 2
257831                    2.0              0.0          9                 2
257847                    2.0              0.0         16                 7

       CRASH_MONTH  LATITUDE LONGITUDE LOCATION
362              1       NaN       NaN      NaN
434              1       NaN       NaN      NaN
893              1       NaN       NaN      NaN
1322             1       NaN       NaN      NaN
1586             1       NaN       NaN      NaN
...            ...       ...       ...      ...
257407           9       NaN       NaN      NaN
257568           8       NaN       NaN      NaN
257751           8       NaN       NaN      NaN
257831           8       NaN       NaN      NaN
257847           8       NaN       NaN      NaN

[1022 rows x 36 columns]

In [12]:
grouped = crashes.groupby(['STREET_NO', 'STREET_DIRECTION', 'STREET_NAME'])

inconsistencies = grouped.filter(lambda x: x[['LATITUDE', 'LONGITUDE']].nunique().max() > 1)

print(inconsistencies)

Empty DataFrame
Columns: [RD_NO, CRASH_DATE, POSTED_SPEED_LIMIT, TRAFFIC_CONTROL_DEVICE, DEVICE_CONDITION, WEATHER_CONDITION, LIGHTING_CONDITION, FIRST_CRASH_TYPE, TRAFFICWAY_TYPE, ALIGNMENT, ROADWAY_SURFACE_COND, ROAD_DEFECT, REPORT_TYPE, CRASH_TYPE, DATE_POLICE_NOTIFIED, PRIM_CONTRIBUTORY_CAUSE, SEC_CONTRIBUTORY_CAUSE, STREET_NO, STREET_DIRECTION, STREET_NAME, BEAT_OF_OCCURRENCE, NUM_UNITS, MOST_SEVERE_INJURY, INJURIES_TOTAL, INJURIES_FATAL, INJURIES_INCAPACITATING, INJURIES_NON_INCAPACITATING, INJURIES_REPORTED_NOT_EVIDENT, INJURIES_NO_INDICATION, INJURIES_UNKNOWN, CRASH_HOUR, CRASH_DAY_OF_WEEK, CRASH_MONTH, LATITUDE, LONGITUDE, LOCATION]
Index: []

[0 rows x 36 columns]

In [11]:
count_duplicates = crashes.groupby(['STREET_NAME']).size().reset_index(name='COUNT')

count_duplicates

     STREET_NAME  COUNT
0       100TH PL     34
1       100TH ST    150
2       101ST PL      7
3       101ST ST     53
4       102ND PL      5
...          ...    ...
1474    YALE AVE    150
1475   YATES AVE     28
1476  YATES BLVD    357
1477  YOUNG PKWY      1
1478    ZEMKE RD      5

[1479 rows x 2 columns]

In [13]:
null_street_name = crashes[crashes['STREET_NAME'].isnull()]
null_street_name

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
226526,HZ386509,08/10/2016 02:20:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,14,4,8,NaN,NaN,NaN

In [24]:
null_street_dir = crashes[crashes['STREET_DIRECTION'].isnull()]
null_street_dir['STREET_NAME']

180006           DOTY AVE W
216083    BESSIE COLEMAN DR
Name: STREET_NAME, dtype: object

In [7]:
dotyave = crashes[crashes['STREET_NAME'] == 'DOTY AVE W']
dotyave['STREET_DIRECTION'].value_counts()

STREET_DIRECTION
S    91
Name: count, dtype: int64

In [8]:
dotyave = crashes[crashes['STREET_NAME'] == 'BESSIE COLEMAN DR']
dotyave['STREET_DIRECTION'].value_counts()

STREET_DIRECTION
N    32
Name: count, dtype: int64

riga 180006 STREET_NAME DOTY AVE W - STREET_DIRECTION S

riga 216083 STREET_NAME BESSIE COLEMAN DR - STREET_DIRECTION N

In [35]:
null_beat_occ = crashes[crashes['BEAT_OF_OCCURRENCE'].isnull()]
null_beat_occ[['STREET_NAME', 'STREET_DIRECTION', 'STREET_NO', 'LOCATION', 'BEAT_OF_OCCURRENCE']]

,STREET_NAME,STREET_DIRECTION,STREET_NO,LOCATION,BEAT_OF_OCCURRENCE
204846,63RD ST,E,425,POINT (-87.614552135332 41.780148264311),NaN
206421,MAY ST,S,5900,POINT (-87.653621088745 41.786811402722),NaN
216083,BESSIE COLEMAN DR,NaN,10000,NaN,NaN
216644,LINCOLN AVE,N,6199,POINT (-87.713896783814 41.994542305274),NaN

In [34]:
bess = crashes[crashes['STREET_NAME']=='BESSIE COLEMAN DR']
bess['BEAT_OF_OCCURRENCE'].value_counts()

BEAT_OF_OCCURRENCE
1654.0    32
Name: count, dtype: int64

In [49]:
strada1 = crashes[crashes['STREET_NAME'] == '63RD ST' ]
strada1 = strada1[strada1['STREET_DIRECTION'] == 'E']

strada1['BEAT_OF_OCCURRENCE'].mode()

0    313.0
Name: BEAT_OF_OCCURRENCE, dtype: float64

In [57]:
strada2 = crashes[crashes['STREET_NAME'] == 'MAY ST' ]
strada2 = strada2[strada2['STREET_DIRECTION'] == 'S']

strada2['BEAT_OF_OCCURRENCE'].mode()

0    712.0
Name: BEAT_OF_OCCURRENCE, dtype: float64

In [56]:
strada3 = crashes[crashes['STREET_NAME'] == 'BESSIE COLEMAN DR' ]
strada3['BEAT_OF_OCCURRENCE'].mode()

0    1654.0
Name: BEAT_OF_OCCURRENCE, dtype: float64

In [55]:
strada3['STREET_DIRECTION'].unique()

array(['N', nan], dtype=object)

In [62]:
strada4 = crashes[crashes['STREET_NAME'] == 'LINCOLN AVE' ]
strada4 = strada4[strada4['STREET_DIRECTION'] == 'N']

strada4['BEAT_OF_OCCURRENCE'].mode()

0    2011.0
Name: BEAT_OF_OCCURRENCE, dtype: float64

# PEOPLE DATASET

In [101]:
people = pd.read_csv('C:/Users/al797/Desktop/People.csv')

In [103]:
people.head()

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
0,O561555,DRIVER,JC113649,535742.0,01/12/2019 12:01:00 AM,NaN,NaN,X,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,UNKNOWN,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",6069.089569
1,O561563,DRIVER,JC113627,535738.0,01/11/2019 11:36:00 PM,CHICAGO,IL,M,63.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",6237.638447
2,O561564,DRIVER,JC113627,535741.0,01/11/2019 11:36:00 PM,CHICAGO,IL,M,36.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,DISREGARDED CONTROL DEVICES,NOT OBSCURED,IMPAIRED - ALCOHOL,"TEST PERFORMED, RESULTS UNKNOWN","OVER $1,500",3802.304187
3,O561540,DRIVER,JC113637,535714.0,01/11/2019 11:31:00 PM,NaN,NaN,F,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,NONE,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",3127.680131
4,O561541,DRIVER,JC113637,535718.0,01/11/2019 11:31:00 PM,CHICAGO,IL,F,31.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",2225.886815


VEHICLE_ID                10696
CITY                     143920
STATE                    141976
SEX                        7154
AGE                      160981
SAFETY_EQUIPMENT           1410
AIRBAG_DEPLOYED           10452
EJECTION                   6705
INJURY_CLASSIFICATION       296
DRIVER_ACTION            109766
DRIVER_VISION            109884

### NO VEHICLE: PEDESTRIANS?

In [114]:
novc = people[people['VEHICLE_ID'].isnull()]
person_type_counts = novc['PERSON_TYPE'].value_counts()
person_type_counts

PERSON_TYPE
PEDESTRIAN             6352
BICYCLE                3799
NON-MOTOR VEHICLE       496
NON-CONTACT VEHICLE      43
DRIVER                    6
Name: count, dtype: int64

per i pedoni, bici e non motorizzati mettiamo 0 al vehicle id, per driver e non-contact?

### City, state, sex li possiamo ricavare?

In [154]:
city = people['CITY'].unique()
people[people['CITY'] == 'FLORENCE']

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
184748,O374599,DRIVER,JB243084,360963.0,04/29/2018 08:45:00 PM,FLORENCE,KY,F,33.0,USAGE UNKNOWN,NOT APPLICABLE,NONE,NO INDICATION OF INJURY,OTHER,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",5194.872860
264145,O294696,DRIVER,JB101207,285799.0,01/02/2018 05:10:00 AM,FLORENCE,SC,M,28.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,IMPROPER BACKING,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",2475.262322
274165,O289930,DRIVER,JA554071,281308.0,12/18/2017 02:30:00 PM,FLORENCE,KY,M,58.0,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,UNKNOWN,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",7461.527924
504249,O59108,DRIVER,HZ351634,57195.0,07/13/2016 08:00:00 PM,FLORENCE,KY,M,31.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FOLLOWED TOO CLOSELY,UNKNOWN,UNKNOWN,TEST NOT OFFERED,$500 OR LESS,NaN

#### SAFETY_EQUIPMENT , AIRBAG_DEPLOYED, EJECTION  possono essere messi a 0 per i pedoni, bici, non veichle, ma per il resto?

# Vehicles ds

UNIT_TYPE                  1           X rimosso

VEHICLE_ID             10373

MAKE                   10373

MODEL                  11786

LIC_PLATE_STATE        49629

VEHICLE_YEAR           88655

VEHICLE_DEFECT         10373

VEHICLE_TYPE           10373

VEHICLE_USE            10373

TRAVEL_DIRECTION       10373

MANEUVER               10373

OCCUPANT_CNT           10373

FIRST_CONTACT_POINT    10388

In [127]:
lic = vehicles[vehicles['LIC_PLATE_STATE'].isnull()]
ll = lic['UNIT_TYPE'].value_counts()
ll

UNIT_TYPE
DRIVER                 39144
PEDESTRIAN              6091
BICYCLE                 3761
NON-MOTOR VEHICLE        472
PARKED                    92
NON-CONTACT VEHICLE       62
DRIVERLESS                 6
Name: count, dtype: int64

In [141]:
la = vehicles[vehicles['UNIT_TYPE'] == 'NON-CONTACT VEHICLE']
la['LIC_PLATE_STATE'].value_counts()

LIC_PLATE_STATE
IL    33
XX     6
TN     1
Name: count, dtype: int64

In [131]:
a = vehicles[vehicles['LIC_PLATE_STATE'].isnull()]
a['UNIT_TYPE'].value_counts()

UNIT_TYPE
DRIVER                 39144
PEDESTRIAN              6091
BICYCLE                 3761
NON-MOTOR VEHICLE        472
PARKED                    92
NON-CONTACT VEHICLE       62
DRIVERLESS                 6
Name: count, dtype: int64

In [152]:
chicago_sky = crashes[crashes['STREET_NAME'] =='CHICAGO SKYWAY OB']
chicago_sky_with_location = chicago_sky[chicago_sky['LOCATION'].notnull()]

lat = chicago_sky_with_location['LATITUDE'].mean()
log = chicago_sky_with_location['LONGITUDE'].mean()

lat

41.74227883457143

In [153]:
log

-87.57590929792856

In [159]:
la_salle= crashes[crashes['STREET_NAME'] =='LA SALLE DR']
la_salle_loc = la_s[la_s['LOCATION'].notnull()]

la_salle_lat = la_s_loc['LATITUDE'].mean()
la_salle_log = la_s_loc['LONGITUDE'].mean()

la_s_lat

41.90103851500532

In [160]:
la_s_log

-87.63245768456915

In [8]:
# Inizializza un dizionario per memorizzare i risultati
street_coordinates = {}

street_names = [
    "CHICAGO SKYWAY OB",
    "CHICAGO SKYWAY IB",
    "TERMINAL ST",
    "DR MARTIN LUTHER KING JR SD",
    "OHARE ST",
    "I190 EXPY",
    "OGDEN SD",
    "KENNEDY EXPY IB",
    "PARKING LOT A ST",
    "PARKING LOT G ST",
    "PARKING LOT D ST",
    "MC FETRIDGE DR",
    "RANDOLPH SUB ST",
    "DAN RYAN LOCAL OB",
    "LA SALLE DR",
    "MANNHEIM RD",
    "LOGAN SD",
    "LA SALLE DR /ILLINOIS",
    "SOUTH WATER RAMP",
    "LAWERENCE",
    "N BELMONT AVE LSD XR",
    "MICHIGAN AVE XR",
    "KENNEDY EXPY OB",
    "87TH ST",
    "KEDVALE AVE",
    "LAKE SHORE DR NB",
    "BESSIE COLEMAN DR",
    "DAN RYAN XPRS OB",
    "SHERMAN PARK SD N",
    "ARCHER/LEAVIT",
    "DAMEN AVE VIA",
    "GARLAND CT / LAKE STREET",
    "RWY 22L",
    "MICHIGAN AVE 175 E CHESTNUT AVE",
    "LAKE LOWER ST",
    "DOTY AVE E",
    "UNION ST",
    "WACKER SUB DR",
    "87TH SD",
    "FRANKLIN SD"
]

# Itera per ciascun nome di strada
for street in street_names:
    # Filtra i dati per la strada corrente
    street_data = crashes[crashes['STREET_NAME'] == street]
    # Considera solo le righe con valori di posizione non nulli
    street_data_loc = street_data[street_data['LOCATION'].notnull()]
    
    # Calcola le medie di latitudine e longitudine
    lat_mean = street_data_loc['LATITUDE'].mean()
    lon_mean = street_data_loc['LONGITUDE'].mean()
    
    # Salva i risultati nel dizionario
    street_coordinates[street] = {'latitude': lat_mean, 'longitude': lon_mean}

# Il dizionario 'street_coordinates' contiene ora le coordinate medie per ogni strada

In [9]:
street_coordinates

{'CHICAGO SKYWAY OB': {'latitude': 41.74227883457143,
  'longitude': -87.57590929792856},
 'CHICAGO SKYWAY IB': {'latitude': 41.74227353683332,
  'longitude': -87.57654492987038},
 'TERMINAL ST': {'latitude': nan, 'longitude': nan},
 'DR MARTIN LUTHER KING JR SD': {'latitude': nan, 'longitude': nan},
 'OHARE ST': {'latitude': 41.97620113900001, 'longitude': -87.90530912500004},
 'I190 EXPY': {'latitude': nan, 'longitude': nan},
 'OGDEN SD': {'latitude': nan, 'longitude': nan},
 'KENNEDY EXPY IB': {'latitude': 41.9445149038,
  'longitude': -87.74905055459999},
 'PARKING LOT A ST': {'latitude': nan, 'longitude': nan},
 'PARKING LOT G ST': {'latitude': nan, 'longitude': nan},
 'PARKING LOT D ST': {'latitude': nan, 'longitude': nan},
 'MC FETRIDGE DR': {'latitude': 41.865043402551734,
  'longitude': -87.6173671586207},
 'RANDOLPH SUB ST': {'latitude': 41.884592989666665,
  'longitude': -87.62160521266667},
 'DAN RYAN LOCAL OB': {'latitude': nan, 'longitude': nan},
 'LA SALLE DR': {'latitude': 41.90103851500532,
  'longitude': -87.63245768456915},
 'MANNHEIM RD': {'latitude': 41.98863609599999, 'longitude': -87.8821597974},
 'LOGAN SD': {'latitude': nan, 'longitude': nan},
 'LA SALLE DR /ILLINOIS': {'latitude': nan, 'longitude': nan},
 'SOUTH WATER RAMP': {'latitude': 41.886845844999996,
  'longitude': -87.621254377},
 'LAWERENCE': {'latitude': nan, 'longitude': nan},
 'N BELMONT AVE LSD XR': {'latitude': nan, 'longitude': nan},
 'MICHIGAN AVE XR': {'latitude': nan, 'longitude': nan},
 'KENNEDY EXPY OB': {'latitude': 41.953580825, 'longitude': -87.7301759305},
 '87TH ST': {'latitude': 41.73621988185685, 'longitude': -87.6337419882137},
 'KEDVALE AVE': {'latitude': 41.87563567062, 'longitude': -87.72905901827599},
 'LAKE SHORE DR NB': {'latitude': 41.899861723909424,
  'longitude': -87.62224080009368},
 'BESSIE COLEMAN DR': {'latitude': nan, 'longitude': nan},
 'DAN RYAN XPRS OB': {'latitude': nan, 'longitude': nan},
 'SHERMAN PARK SD N': {'latitude': nan, 'longitude': nan},
 'ARCHER/LEAVIT': {'latitude': nan, 'longitude': nan},
 'DAMEN AVE VIA': {'latitude': nan, 'longitude': nan},
 'GARLAND CT / LAKE STREET': {'latitude': nan, 'longitude': nan},
 'RWY 22L': {'latitude': nan, 'longitude': nan},
 'MICHIGAN AVE 175 E CHESTNUT AVE': {'latitude': nan, 'longitude': nan},
 'LAKE LOWER ST': {'latitude': 41.885688421, 'longitude': -87.62097238825},
 'DOTY AVE E': {'latitude': 41.691178218063584,
  'longitude': -87.59287764128324},
 'UNION ST': {'latitude': nan, 'longitude': nan},
 'WACKER SUB DR': {'latitude': 41.888183762, 'longitude': -87.622614368},
 '87TH SD': {'latitude': nan, 'longitude': nan},
 'FRANKLIN SD': {'latitude': nan, 'longitude': nan}}

In [120]:
vehicles[vehicles['LIC_PLATE_STATE'].isnull()]

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
8,561513,JC113579,01/11/2019 10:45:00 PM,1,DRIVER,535691.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,SPORT UTILITY VEHICLE (SUV),UNKNOWN/NA,S,UNKNOWN/NA,1.0,UNKNOWN
12,561515,JC113568,01/11/2019 10:16:00 PM,1,DRIVER,535692.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,N,UNKNOWN/NA,1.0,UNKNOWN
15,561507,JC113569,01/11/2019 10:00:00 PM,1,DRIVER,535681.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,E,PASSING/OVERTAKING,1.0,UNKNOWN
51,561455,JC113370,01/11/2019 07:10:00 PM,1,DRIVER,535624.0,CHEVROLET,TAHOE,NaN,NaN,UNKNOWN,SPORT UTILITY VEHICLE (SUV),UNKNOWN/NA,E,STRAIGHT AHEAD,1.0,FRONT-RIGHT
55,561409,JC113366,01/11/2019 07:06:00 PM,1,DRIVER,535581.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,PASSENGER,UNKNOWN/NA,S,TURNING LEFT,1.0,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460377,8,HY368496,08/04/2015 10:00:00 AM,1,DRIVER,8.0,VOLKSWAGEN,JETTA,NaN,2008.0,NONE,PASSENGER,PERSONAL,N,CHANGING LANES,1.0,FRONT-RIGHT
460380,6,HY368370,08/04/2015 08:00:00 AM,1,DRIVER,6.0,PONTIAC,BONNEVILLE,NaN,NaN,UNKNOWN,PASSENGER,UNKNOWN/NA,N,STRAIGHT AHEAD,1.0,FRONT
460416,13287,HY507396,05/20/2015 02:24:00 PM,1,DRIVER,12750.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,UNKNOWN,UNKNOWN/NA,1.0,UNKNOWN
460417,146994,JA227271,04/16/2015 10:00:00 PM,1,DRIVER,146407.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,N,STRAIGHT AHEAD,1.0,UNKNOWN
460428,12093,HY498942,11/11/2014 08:00:00 PM,1,DRIVER,11595.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,UNKNOWN,UNKNOWN/NA,1.0,UNKNOWN

In [85]:
a = vehicles[vehicles['VEHICLE_ID'].isnull()]
a['UNIT_TYPE'].value_counts()

UNIT_TYPE
PEDESTRIAN             6091
BICYCLE                3761
NON-MOTOR VEHICLE       472
NON-CONTACT VEHICLE      42
DRIVER                    6
Name: count, dtype: int64

In [118]:
a[a['UNIT_TYPE']=='DRIVER']

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
91168,447299,JB376407,08/02/2018 04:45:00 PM,2,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91744,445864,JB374941,08/01/2018 06:15:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91939,445652,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91940,445653,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91941,445904,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91994,445666,JB374559,08/01/2018 02:19:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
a[a['UNIT_TYPE'] == 'NON-CONTACT VEHICLE']

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
17645,538784,JB545482,12/08/2018 07:21:00 PM,3,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22335,532855,JB535046,11/30/2018 05:15:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32036,520830,JB514012,11/13/2018 08:01:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37446,514021,JB501818,11/03/2018 12:10:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45919,503649,JB482165,10/19/2018 02:00:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54307,492712,JB463468,10/05/2018 11:14:00 AM,3,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64311,480289,JB440461,09/18/2018 11:39:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78340,462919,JB408384,08/25/2018 01:10:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95531,448833,JB380341,07/26/2018 06:50:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113877,417796,JB321344,06/25/2018 01:20:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131718,395805,JB281096,05/27/2018 03:26:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141216,384013,JB260182,05/11/2018 10:43:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143943,381628,JB255807,05/07/2018 04:45:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144727,379659,JB252292,05/06/2018 11:35:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148042,375642,JB244952,05/01/2018 08:45:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163022,357104,JB211847,04/04/2018 10:23:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171052,347069,JB193391,03/20/2018 05:50:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177575,339397,JB179268,03/08/2018 09:30:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183429,332277,JB166468,02/26/2018 05:25:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199621,311828,JB130530,01/26/2018 02:30:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215841,292640,JA566812,12/29/2017 02:00:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222681,283654,JA552149,12/16/2017 10:25:00 PM,3,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225128,280814,JA547497,12/13/2017 07:45:00 AM,3,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231413,272934,JA533437,12/02/2017 08:58:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242096,259828,JA508711,11/12/2017 06:05:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248013,252471,JA496235,11/02/2017 05:00:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249116,251225,JA494185,11/01/2017 09:15:00 AM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251137,248670,JA489303,10/28/2017 11:28:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255868,249256,JA487945,10/20/2017 04:00:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261902,239888,JA467702,10/10/2017 05:00:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268278,227699,JA451437,09/29/2017 01:00:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284689,207428,JA410394,08/29/2017 09:48:00 AM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285534,206331,JA407879,08/27/2017 06:22:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310654,175753,JA323501,06/26/2017 12:00:00 PM,2,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311764,174397,JA318880,06/23/2017 06:15:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320507,164903,JA288495,05/31/2017 06:00:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328922,170925,JA307159,05/05/2017 06:00:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331892,151572,JA241341,04/27/2017 09:20:00 AM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345917,138499,JA182370,03/10/2017 04:15:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363131,114032,JA103121,01/03/2017 03:40:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379351,94910,HZ505126,11/06/2016 02:30:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387641,86138,HZ472716,10/10/2016 02:00:00 PM,1,NON-CONTACT VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
crashes[crashes['RD_NO']=='JB545482']

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
9905,JB545482,12/08/2018 07:21:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,19,7,12,41.880328,-87.749961,POINT (-87.749961029766 41.880327970591)

In [97]:
people[people['RD_NO']=='JB535046']

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
27681,O532828,DRIVER,JB535046,508785.0,11/30/2018 05:15:00 PM,CHICAGO,IL,M,29.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FOLLOWED TOO CLOSELY,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",1912.444606
27682,O532829,DRIVER,JB535046,508794.0,11/30/2018 05:15:00 PM,HINSDALE,IL,F,49.0,SAFETY BELT USED,"DEPLOYED OTHER (KNEE, AIR, BELT, ETC.)",NONE,NO INDICATION OF INJURY,OTHER,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",2279.555232
27683,O532855,NON-CONTACT VEHICLE,JB535046,NaN,11/30/2018 05:15:00 PM,NaN,NaN,NaN,NaN,NONE PRESENT,NaN,NONE,NO INDICATION OF INJURY,OTHER,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",3873.965862

##### Unit type

In [83]:
unittype = vehicles['CRASH_UNIT_ID']
unittype

0         561555
1         561563
2         561564
3         561540
4         561541
           ...
460432     30751
460433     24495
460434     24496
460435    481321
460436    481322
Name: CRASH_UNIT_ID, Length: 460437, dtype: int64

In [84]:
people['PERSON_ID']

0         O561555
1         O561563
2         O561564
3         O561540
4         O561541
           ...
564560     O30751
564561     O24495
564562     O24496
564563    O481321
564564    P108071
Name: PERSON_ID, Length: 564565, dtype: object

In [78]:
vehicles['UNIT_TYPE'].value_counts()

UNIT_TYPE
DRIVER                 444982
PEDESTRIAN               6091
PARKED                   4827
BICYCLE                  3761
NON-MOTOR VEHICLE         472
DRIVERLESS                201
NON-CONTACT VEHICLE       102
Name: count, dtype: int64

In [76]:
crashes[crashes['RD_NO']=='JB374571']

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
51567,JB374571,08/01/2018 02:59:00 PM,25,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,6.0,0.0,14,4,8,41.940077,-87.650295,POINT (-87.650294867996 41.940076854718)

In [163]:
unitnull = people[people['RD_NO'] == 'JB374571']
unitnull['VEHICLE_ID']

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
113587,O445609,BICYCLE,JB374571,NaN,08/01/2018 02:59:00 PM,HOFFMAN ESTATES,IL,M,26.0,NONE PRESENT,NaN,NONE,NONINCAPACITATING INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,$500 OR LESS,NaN
113588,O445620,DRIVER,JB374571,427330.0,08/01/2018 02:59:00 PM,DES PLAINES,IL,F,59.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED,$500 OR LESS,NaN
113589,O445652,DRIVER,JB374571,NaN,08/01/2018 02:59:00 PM,DES PLAINES,IL,F,59.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED,$500 OR LESS,NaN
113590,O445653,DRIVER,JB374571,NaN,08/01/2018 02:59:00 PM,DES PLAINES,IL,F,59.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED,$500 OR LESS,NaN
113591,O445667,DRIVER,JB374571,427349.0,08/01/2018 02:59:00 PM,DES PLAINES,IL,F,59.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED,$500 OR LESS,NaN
113592,O445904,DRIVER,JB374571,NaN,08/01/2018 02:59:00 PM,DES PLAINES,IL,F,59.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED,$500 OR LESS,NaN
113593,P100689,PASSENGER,JB374571,427330.0,08/01/2018 02:59:00 PM,DES PLAINES,IL,F,22.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,$500 OR LESS,NaN

In [167]:
passe = people[people['PERSON_TYPE'] == 'PASSENGER']
passe

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
8,P126669,PASSENGER,JC113604,535703.0,01/11/2019 11:08:00 PM,NaN,NaN,F,NaN,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",1702.584614
11,P126665,PASSENGER,JC113579,535694.0,01/11/2019 10:45:00 PM,CHICAGO,IL,F,29.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",7056.834554
14,P126674,PASSENGER,JC113617,535725.0,01/11/2019 10:28:00 PM,CHICAGO,IL,F,39.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",2090.583708
22,P126663,PASSENGER,JC113528,535688.0,01/11/2019 09:35:00 PM,CHICAGO,IL,F,18.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",4293.840357
23,P126664,PASSENGER,JC113528,535678.0,01/11/2019 09:35:00 PM,CHICAGO,IL,M,25.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",2493.790294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564533,P11,PASSENGER,HY372446,59.0,07/07/2015 03:15:00 PM,CHICAGO,IL,F,69.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",2721.754111
564535,P20,PASSENGER,HY372966,83.0,07/04/2015 12:15:00 AM,CHICAGO,IL,M,24.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"$501 - $1,500",1408.049718
564539,P887,PASSENGER,HY451313,4677.0,06/22/2015 02:30:00 PM,NaN,NaN,M,NaN,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",5342.445322
564540,P888,PASSENGER,HY451313,4682.0,06/22/2015 02:30:00 PM,NaN,MN,M,NaN,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",3809.324686
564564,P108071,PASSENGER,JB442550,460661.0,01/18/2014 06:14:00 PM,CHICAGO,IL,M,41.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",6589.530915

In [169]:
people[people['RD_NO']=='JC113528']

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
20,O561505,DRIVER,JC113528,535678.0,01/11/2019 09:35:00 PM,NaN,NaN,M,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",3335.028867
21,O561506,DRIVER,JC113528,535688.0,01/11/2019 09:35:00 PM,OAKLAWN,IL,M,50.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",4592.998567
22,P126663,PASSENGER,JC113528,535688.0,01/11/2019 09:35:00 PM,CHICAGO,IL,F,18.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",4293.840357
23,P126664,PASSENGER,JC113528,535678.0,01/11/2019 09:35:00 PM,CHICAGO,IL,M,25.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",2493.790294

In [168]:
vehicles[vehicles['RD_NO']=='JC113528']

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
17,561505,JC113528,01/11/2019 09:35:00 PM,1,DRIVER,535678.0,PONTIAC,GRAND PRIX,IL,1999.0,UNKNOWN,PASSENGER,PERSONAL,E,AVOIDING VEHICLES/OBJECTS,2.0,FRONT-LEFT
18,561506,JC113528,01/11/2019 09:35:00 PM,2,DRIVER,535688.0,PONTIAC,G6,IL,2006.0,NONE,PASSENGER,PERSONAL,S,TURNING LEFT,2.0,SIDE-RIGHT

In [166]:
vehicles['UNIT_TYPE'].unique()

array(['DRIVER', 'PARKED', 'PEDESTRIAN', 'BICYCLE', 'NON-MOTOR VEHICLE',
       'DRIVERLESS', 'NON-CONTACT VEHICLE', nan], dtype=object)

considerando che i passeggeri coinvolti negli incidenti non sono riportati nel ds vehicles, abbiamo deciso di rimuovere la riga

vehicle

In [184]:
vehicle3 = vehicles.sort_values(by='VEHICLE_ID')
# Rimuoviamo i valori nulli
vehicles2 = vehicle3['VEHICLE_ID'].dropna()

# Controlla se i valori sono progressivi
progressive = (vehicles2.diff().fillna(0) >= 0).all()

# Mostra il risultato
if progressive:
    print("I valori nella colonna (escludendo i nulli) sono progressivi.")
else:
    print("I valori nella colonna (escludendo i nulli) NON sono progressivi.")

I valori nella colonna (escludendo i nulli) sono progressivi.

In [186]:
vehicles2

460383         2.0
460384         3.0
460382         4.0
460380         6.0
460381         7.0
            ...
10        535723.0
11        535725.0
1         535738.0
2         535741.0
0         535742.0
Name: VEHICLE_ID, Length: 450064, dtype: float64

In [59]:
colonne = ['VEHICLE_ID', 'MAKE', 'VEHICLE_DEFECT', 'VEHICLE_TYPE', 
           'VEHICLE_USE', 'TRAVEL_DIRECTION', 'MANEUVER', 'OCCUPANT_CNT']

df_null = vehicles[colonne].isnull()

righe_con_null = df_null.all(axis=1)

righe_con_tutti_null = vehicles[righe_con_null]

righe_con_tutti_null['UNIT_TYPE'].value_counts()

UNIT_TYPE
PEDESTRIAN             6091
BICYCLE                3761
NON-MOTOR VEHICLE       472
NON-CONTACT VEHICLE      42
DRIVER                    6
Name: count, dtype: int64

##### 10373 righe hanno valori nulli per le colonne: VEHICLE_ID, MAKE, VEHICLE_DEFECT,VEHICLE_TYPE, VEHICLE_USE, TRAVEL_DIRECTION, MANEUVER, OCCUPANT_CNT perchè sono tutti pedoni/bici/senza macchina

In [104]:
vehicles['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT                98284
REAR                 70325
FRONT-RIGHT          61541
FRONT-LEFT           57494
UNKNOWN              44917
SIDE-RIGHT           30397
SIDE-LEFT            26482
REAR-LEFT            25857
REAR-RIGHT           24029
NONE                  5379
OTHER                 1962
TOTAL (ALL AREAS)     1903
UNDER CARRIAGE         829
ROOF                   650
Name: count, dtype: int64

In [111]:
vv = vehicles[vehicles['UNIT_TYPE']== 'BICYCLE']
vv['FIRST_CONTACT_POINT'].value_counts()

Series([], Name: count, dtype: int64)

In [117]:
no_fcp = vehicles[vehicles['FIRST_CONTACT_POINT'].isnull()] 
no_fcp['UNIT_TYPE'].value_counts()

UNIT_TYPE
PEDESTRIAN             6091
BICYCLE                3761
NON-MOTOR VEHICLE       472
NON-CONTACT VEHICLE      55
DRIVER                    8
Name: count, dtype: int64

In [115]:
no_fcp[no_fcp['MANEUVER']== 'TURNING LEFT']

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
45241,504128,JB483067,10/20/2018 01:00:00 PM,1,NON-CONTACT VEHICLE,481896.0,"TOYOTA MOTOR COMPANY, LTD.",UNKNOWN,IL,2006.0,UNKNOWN,SPORT UTILITY VEHICLE (SUV),UNKNOWN/NA,S,TURNING LEFT,1.0,NaN
82970,457027,JB396892,08/17/2018 06:00:00 AM,1,NON-CONTACT VEHICLE,437982.0,FORD,ESCAPE (SUV),IL,2015.0,NONE,PASSENGER,PERSONAL,N,TURNING LEFT,1.0,NaN
91902,445854,JB374667,08/01/2018 03:30:00 PM,1,DRIVER,427436.0,UNKNOWN,UNKNOWN,IL,2010.0,UNKNOWN,BUS OVER 15 PASS.,SCHOOL BUS,SW,TURNING LEFT,1.0,NaN
426504,39547,HZ219490,04/09/2016 01:45:00 PM,1,NON-CONTACT VEHICLE,38224.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,SPORT UTILITY VEHICLE (SUV),PERSONAL,N,TURNING LEFT,1.0,NaN

In [116]:
no_fcp[no_fcp['MANEUVER']== 'STRAIGHT AHEAD']

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
77036,464430,JB411220,08/27/2018 05:20:00 PM,1,NON-CONTACT VEHICLE,444855.0,NISSAN,Frontier,TN,2002.0,NONE,PICKUP,PERSONAL,S,STRAIGHT AHEAD,1.0,NaN
210423,298723,JB106709,01/06/2018 03:05:00 PM,3,NON-CONTACT VEHICLE,289535.0,UNKNOWN,UNKNOWN,NaN,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,W,STRAIGHT AHEAD,1.0,NaN
237076,265869,JA519355,11/20/2017 04:30:00 PM,1,NON-CONTACT VEHICLE,258570.0,UNKNOWN,UNKNOWN,NaN,NaN,NONE,UNKNOWN/NA,UNKNOWN/NA,W,STRAIGHT AHEAD,1.0,NaN
356772,138972,JA133212,01/28/2017 01:35:00 PM,3,NON-CONTACT VEHICLE,138655.0,HONDA,ACCORD,IL,2008.0,UNKNOWN,PASSENGER,UNKNOWN/NA,W,STRAIGHT AHEAD,1.0,NaN

###### togliendo queste righe sopra, gli altri 10373 sono pedoni/bici/senza veicolo a motore

In [98]:
tur_left = vehicles[vehicles['MANEUVER'] == 'TURNING LEFT']
tur_left['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT-RIGHT          6722
FRONT-LEFT           5660
FRONT                5143
SIDE-RIGHT           2471
SIDE-LEFT            2363
REAR-RIGHT           2135
REAR-LEFT            1881
UNKNOWN              1305
REAR                  776
NONE                  372
OTHER                 101
TOTAL (ALL AREAS)     101
UNDER CARRIAGE         25
ROOF                   17
Name: count, dtype: int64

In [99]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'STRAIGHT AHEAD']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT                70902
FRONT-RIGHT          33085
REAR                 28073
FRONT-LEFT           27704
SIDE-RIGHT           17340
SIDE-LEFT            14205
UNKNOWN              11399
REAR-LEFT            10550
REAR-RIGHT           10223
NONE                  2681
TOTAL (ALL AREAS)     1304
OTHER                 1126
UNDER CARRIAGE         556
ROOF                   507
Name: count, dtype: int64

In [18]:
noc = vehicles[vehicles['OCCUPANT_CNT'].isnull()]
aaa = noc[noc['UNIT_TYPE']=='DRIVER']
aaa

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
91168,447299,JB376407,08/02/2018 04:45:00 PM,2,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91744,445864,JB374941,08/01/2018 06:15:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91939,445652,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91940,445653,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91941,445904,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91994,445666,JB374559,08/01/2018 02:19:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
aaaaa = vehicles[vehicles['VEHICLE_TYPE'].isnull()]
aaaaa[aaaaa['UNIT_TYPE']=='DRIVER']

,CRASH_UNIT_ID,RD_NO,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,LIC_PLATE_STATE,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
91168,447299,JB376407,08/02/2018 04:45:00 PM,2,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91744,445864,JB374941,08/01/2018 06:15:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91939,445652,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91940,445653,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91941,445904,JB374571,08/01/2018 02:59:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91994,445666,JB374559,08/01/2018 02:19:00 PM,1,DRIVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
vehicles['VEHICLE_TYPE'].value_counts()

VEHICLE_TYPE
PASSENGER                      281639
SPORT UTILITY VEHICLE (SUV)     57604
UNKNOWN/NA                      46246
VAN/MINI-VAN                    23953
PICKUP                          12563
TRUCK - SINGLE UNIT              9022
BUS OVER 15 PASS.                5501
OTHER                            5171
TRACTOR W/ SEMI-TRAILER          4447
BUS UP TO 15 PASS.                967
MOTORCYCLE (OVER 150CC)           828
OTHER VEHICLE WITH TRAILER        721
TRACTOR W/O SEMI-TRAILER          583
AUTOCYCLE                         502
MOTOR DRIVEN CYCLE                252
ALL-TERRAIN VEHICLE (ATV)          31
FARM EQUIPMENT                     28
SNOWMOBILE                          6
Name: count, dtype: int64

In [33]:
aaa = vehicles[vehicles['UNIT_TYPE']=='NON-MOTOR VEHICLE']
aaa['MANEUVER'].value_counts()

Series([], Name: count, dtype: int64)

In [100]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'CHANGING LANES']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT-RIGHT          3492
FRONT-LEFT           2416
SIDE-RIGHT           1275
SIDE-LEFT             969
UNKNOWN               834
REAR-LEFT             833
REAR-RIGHT            651
FRONT                 505
REAR                  161
NONE                  122
TOTAL (ALL AREAS)      43
OTHER                  33
UNDER CARRIAGE          5
ROOF                    1
Name: count, dtype: int64

In [101]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'U-TURN']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT-LEFT           687
FRONT                443
SIDE-LEFT            397
FRONT-RIGHT          389
REAR-LEFT            290
UNKNOWN              202
REAR-RIGHT           104
SIDE-RIGHT            84
REAR                  66
NONE                  26
TOTAL (ALL AREAS)     11
UNDER CARRIAGE         5
OTHER                  4
ROOF                   1
Name: count, dtype: int64

In [102]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'SLOW/STOP IN TRAFFIC']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
REAR                 24409
FRONT                 5871
REAR-LEFT             3000
FRONT-LEFT            2124
REAR-RIGHT            2121
FRONT-RIGHT           1478
SIDE-LEFT             1370
SIDE-RIGHT             940
UNKNOWN                461
NONE                   304
OTHER                  123
TOTAL (ALL AREAS)       75
ROOF                     9
UNDER CARRIAGE           7
Name: count, dtype: int64

In [103]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'PARKED IN TRAFFIC LANE']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
SIDE-LEFT            65
REAR-LEFT            58
FRONT-LEFT           53
FRONT                23
SIDE-RIGHT           23
REAR                 12
REAR-RIGHT           12
FRONT-RIGHT          10
UNKNOWN               9
NONE                  3
OTHER                 2
TOTAL (ALL AREAS)     1
Name: count, dtype: int64

# PEOPLE DATASET

In [7]:
people

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
0,O561555,DRIVER,JC113649,535742.0,01/12/2019 12:01:00 AM,NaN,NaN,X,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,UNKNOWN,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",6069.089569
1,O561563,DRIVER,JC113627,535738.0,01/11/2019 11:36:00 PM,CHICAGO,IL,M,63.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",6237.638447
2,O561564,DRIVER,JC113627,535741.0,01/11/2019 11:36:00 PM,CHICAGO,IL,M,36.0,USAGE UNKNOWN,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,DISREGARDED CONTROL DEVICES,NOT OBSCURED,IMPAIRED - ALCOHOL,"TEST PERFORMED, RESULTS UNKNOWN","OVER $1,500",3802.304187
3,O561540,DRIVER,JC113637,535714.0,01/11/2019 11:31:00 PM,NaN,NaN,F,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,NONE,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",3127.680131
4,O561541,DRIVER,JC113637,535718.0,01/11/2019 11:31:00 PM,CHICAGO,IL,F,31.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",2225.886815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564560,O30751,DRIVER,HZ164689,29701.0,02/24/2014 07:45:00 PM,CHICAGO,IL,M,33.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"$501 - $1,500",1436.117669
564561,O24495,DRIVER,HZ122950,23633.0,01/21/2014 07:40:00 AM,CHICAGO,IL,F,36.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",2713.810276
564562,O24496,DRIVER,HZ122950,23634.0,01/21/2014 07:40:00 AM,CHICAGO,IL,F,41.0,SAFETY BELT USED,"DEPLOYED, FRONT",NONE,NONINCAPACITATING INJURY,NONE,NOT OBSCURED,NORMAL,TEST NOT OFFERED,"OVER $1,500",8248.141026
564563,O481321,DRIVER,JB442550,460655.0,01/18/2014 06:14:00 PM,NaN,NaN,M,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,IMPROPER PARKING,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",1940.156103
564564,P108071,PASSENGER,JB442550,460661.0,01/18/2014 06:14:00 PM,CHICAGO,IL,M,41.0,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN,"OVER $1,500",6589.530915

In [22]:
no_vehicle = people[people['VEHICLE_ID'].isnull()]

In [29]:
no_vehicle['PERSON_TYPE'].unique()

array(['PEDESTRIAN', 'BICYCLE', 'NON-MOTOR VEHICLE',
       'NON-CONTACT VEHICLE', 'DRIVER'], dtype=object)

In [25]:
no_v_ped = no_vehicle[no_vehicle['PERSON_TYPE'] == 'PEDESTRIAN']

In [27]:
no_v_ped = no_vehicle[no_vehicle['PERSON_TYPE'] == 'BICYCLE']

In [30]:
no_v_ped = no_vehicle[no_vehicle['PERSON_TYPE'] == 'NON-MOTOR VEHICLE']

In [31]:
no_v_ped

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
731,O560442,NON-MOTOR VEHICLE,JC111323,NaN,01/10/2019 08:20:00 AM,CHICAGO,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEST NOT OFFERED,"OVER $1,500",5068.411467
973,O560224,NON-MOTOR VEHICLE,JC110823,NaN,01/09/2019 04:06:00 PM,CHICAGO,IL,M,NaN,NaN,NaN,NaN,NaN,NONE,UNKNOWN,UNKNOWN,TEST NOT OFFERED,$500 OR LESS,NaN
5551,O555314,NON-MOTOR VEHICLE,JC100471,NaN,01/01/2019 01:30:00 AM,CHICAGO,IL,M,47.0,NONE PRESENT,NOT APPLICABLE,NONE,NO INDICATION OF INJURY,NONE,UNKNOWN,NORMAL,TEST NOT OFFERED,"OVER $1,500",2498.281436
10362,O550465,NON-MOTOR VEHICLE,JB566159,NaN,12/24/2018 01:39:00 PM,CHICAGO,IL,X,NaN,NaN,NaN,NaN,NaN,NONE,OTHER,OTHER,TEST NOT OFFERED,"OVER $1,500",3858.894693
10363,O550465,NON-MOTOR VEHICLE,JB566159,NaN,12/24/2018 01:39:00 PM,CHICAGO,IL,X,NaN,NaN,NaN,NaN,NaN,NONE,OTHER,OTHER,TEST NOT OFFERED,"OVER $1,500",3420.168243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561096,O3391,NON-MOTOR VEHICLE,HY437811,NaN,09/25/2015 12:05:00 PM,CHICAGO,IL,NaN,NaN,NONE PRESENT,NOT APPLICABLE,NONE,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED,"OVER $1,500",1610.628995
562022,O2817,NON-MOTOR VEHICLE,HY431905,NaN,09/18/2015 08:00:00 AM,CHICAGO,IL,U,NaN,NONE PRESENT,NOT APPLICABLE,NONE,NO INDICATION OF INJURY,NONE,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",4819.160463
562739,O1742,NON-MOTOR VEHICLE,HY419234,NaN,09/11/2015 07:35:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEST NOT OFFERED,"$501 - $1,500",1049.958548
563047,O1661,NON-MOTOR VEHICLE,HY418182,NaN,09/08/2015 12:00:00 PM,CHICAGO,IL,M,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN,TEST NOT OFFERED,"OVER $1,500",2342.211682
563573,O1156,NON-MOTOR VEHICLE,HY410181,NaN,08/31/2015 02:30:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEST NOT OFFERED,"OVER $1,500",2326.854166

In [32]:
no_saf = people[people['SAFETY_EQUIPMENT'].isnull()]

In [36]:
no_saf['PERSON_TYPE'].unique()

array(['PEDESTRIAN', 'NON-MOTOR VEHICLE', 'PASSENGER', 'BICYCLE',
       'NON-CONTACT VEHICLE'], dtype=object)

In [35]:
no_saf[no_saf['PERSON_TYPE']=='PASSENGER']

,PERSON_ID,PERSON_TYPE,RD_NO,VEHICLE_ID,CRASH_DATE,CITY,STATE,SEX,AGE,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,BAC_RESULT,DAMAGE_CATEGORY,DAMAGE
16148,P122575,PASSENGER,JB555457,519710.0,12/16/2018 06:00:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",2860.739556
31603,P119027,PASSENGER,JB528366,505038.0,11/25/2018 12:15:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501 - $1,500",1448.892996
31604,P119029,PASSENGER,JB528366,505042.0,11/25/2018 12:15:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501 - $1,500",1072.090036
36851,P118597,PASSENGER,JB525110,503534.0,11/16/2018 06:00:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",3688.913122
37245,P117700,PASSENGER,JB518098,499741.0,11/16/2018 09:00:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$500 OR LESS,NaN
44978,P115939,PASSENGER,JB504023,492363.0,11/05/2018 12:30:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$500 OR LESS,NaN
70099,P109995,PASSENGER,JB457828,468281.0,10/01/2018 08:40:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",5516.244913
116645,P99061,PASSENGER,JB368561,424558.0,07/27/2018 11:30:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",2908.789875
122136,P97639,PASSENGER,JB357618,419320.0,07/20/2018 11:14:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",3186.737144
136366,P94210,PASSENGER,JB330225,405702.0,07/01/2018 04:01:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",2827.493768
209661,P76633,PASSENGER,JB198056,337418.0,03/24/2018 12:40:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",3491.910850
213626,P75813,PASSENGER,JB191679,334170.0,03/18/2018 01:20:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",1738.022996
223310,P73358,PASSENGER,JB173040,324548.0,03/04/2018 07:24:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",3762.574104
224047,P73147,PASSENGER,JB171822,323867.0,03/03/2018 04:02:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501 - $1,500",1059.779018
228042,P72171,PASSENGER,JB164514,320114.0,02/25/2018 04:00:00 AM,NaN,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",2259.772550
229344,P71849,PASSENGER,JB162390,318956.0,02/23/2018 11:12:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",3212.938809
236030,P70426,PASSENGER,JB150393,312498.0,02/13/2018 10:45:00 AM,NaN,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$500 OR LESS,NaN
236176,P70394,PASSENGER,JB150159,312307.0,02/13/2018 07:40:00 AM,NaN,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OVER $1,500",2195.292966

In [49]:
no_air = people[people['AIRBAG_DEPLOYED'].isnull()]
no_air['PERSON_TYPE'].value_counts()

PERSON_TYPE
PEDESTRIAN             6352
BICYCLE                3799
NON-MOTOR VEHICLE       259
NON-CONTACT VEHICLE      23
PASSENGER                19
Name: count, dtype: int64

In [56]:
no_air = people[people['EJECTION'].isnull()]
no_air['PERSON_TYPE'].value_counts()

PERSON_TYPE
PEDESTRIAN             6352
NON-MOTOR VEHICLE       242
BICYCLE                  71
PASSENGER                20
NON-CONTACT VEHICLE      20
Name: count, dtype: int64

In [62]:
no_inj = people[people['INJURY_CLASSIFICATION'].isnull()]
people['INJURY_CLASSIFICATION'].value_counts()

INJURY_CLASSIFICATION
NO INDICATION OF INJURY     524430
NONINCAPACITATING INJURY     21334
REPORTED, NOT EVIDENT        13843
INCAPACITATING INJURY         4426
FATAL                          236
Name: count, dtype: int64

In [63]:
no_air = people[people['DRIVER_ACTION'].isnull()]
no_air['PERSON_TYPE'].value_counts()

PERSON_TYPE
PASSENGER              108833
PEDESTRIAN                589
NON-MOTOR VEHICLE         240
BICYCLE                    88
NON-CONTACT VEHICLE        16
Name: count, dtype: int64

In [64]:
people['DRIVER_ACTION'].value_counts()

DRIVER_ACTION
NONE                                 171361
UNKNOWN                               97822
FAILED TO YIELD                       45427
OTHER                                 36727
FOLLOWED TOO CLOSELY                  32432
IMPROPER BACKING                      15534
IMPROPER LANE CHANGE                  13214
IMPROPER TURN                         12291
IMPROPER PASSING                      10452
TOO FAST FOR CONDITIONS                7348
DISREGARDED CONTROL DEVICES            6509
IMPROPER PARKING                       1858
WRONG WAY/SIDE                         1531
CELL PHONE USE OTHER THAN TEXTING       881
EVADING POLICE VEHICLE                  744
EMERGENCY VEHICLE ON CALL               369
TEXTING                                 222
STOPPED SCHOOL BUS                       63
LICENSE RESTRICTIONS                     14
Name: count, dtype: int64

In [73]:
p = people[people['PERSON_TYPE'] == 'DRIVER']
p['VEHICLE_ID'].value_counts()

VEHICLE_ID
535742.0    1
176399.0    1
176366.0    1
176606.0    1
176609.0    1
           ..
354314.0    1
354397.0    1
354387.0    1
354382.0    1
460655.0    1
Name: count, Length: 444976, dtype: int64

In [172]:
driv = vehicles[vehicles['UNIT_TYPE']=='DRIVER']
driv['VEHICLE_YEAR'].value_counts()

VEHICLE_YEAR
2015.0    30415
2014.0    28169
2016.0    27090
2013.0    25917
2012.0    22523
          ...
2994.0        1
2203.0        1
2914.0        1
2402.0        1
1962.0        1
Name: count, Length: 131, dtype: int64

In [171]:
null_year = vehicles[vehicles['VEHICLE_YEAR'].isnull()]
null_year['MODEL'].value_counts()

MODEL
UNKNOWN                                   54615
CAMRY                                       927
NISSAN ALTIMA                               720
IMPALA                                      667
MALIBU (CHEVELLE)                           601
                                          ...
HILBILT MFG. CO., BENTON, ARKANSAS            1
TURNPIKE CRUISER                              1
LABARON                                       1
RSX                                           1
AZTEC PRODUCTS, INC., MANSFIELD, TEXAS        1
Name: count, Length: 862, dtype: int64

In [11]:
cleaned_crashes = pd.read_csv('C:/Users/al797/Desktop/cleaned_crashes.csv')

In [12]:
cleaned_crashes

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,JC113649,01/12/2019 12:01:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,0,7,1,41.894718,-87.716439,POINT (-87.716439109795 41.894718028422)
1,JC113627,01/11/2019 11:36:00 PM,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,1,41.961558,-87.757564,POINT (-87.757564024038 41.961557797444)
2,JC113637,01/11/2019 11:31:00 PM,15,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,DARKNESS,SIDESWIPE OPPOSITE DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,23,6,1,41.791460,-87.715908,POINT (-87.715907858157 41.791459913725)
3,JC113630,01/11/2019 11:22:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,DARKNESS,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,23,6,1,41.876779,-87.741695,POINT (-87.741694507685 41.876778736117)
4,JC113604,01/11/2019 11:08:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,3.0,0.0,23,6,1,41.960921,-87.739893,POINT (-87.739893056441 41.960920858153)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257920,HY498942,11/11/2014 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,1.0,0.0,20,3,11,41.998270,-87.662997,POINT (-87.662996825424 41.998269693725)
257921,HZ400518,08/20/2014 04:50:00 PM,0,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,16,4,8,41.751143,-87.607091,POINT (-87.607090627909 41.751143217534)
257922,HZ164689,02/24/2014 07:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,19,2,2,41.884016,-87.701143,POINT (-87.701142757538 41.884016475152)
257923,HZ122950,01/21/2014 07:40:00 AM,30,YIELD,NO CONTROLS,CLEAR,DAYLIGHT,ANGLE,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,1.0,0.0,1.0,0.0,7,3,1,41.760710,-87.561946,POINT (-87.561946030143 41.760710194223)
257924,JB442550,01/18/2014 06:14:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DUSK,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,0.0,0.0,2.0,0.0,18,7,1,41.885610,-87.638756,POINT (-87.638756189808 41.885609917063)

In [15]:
has_nulls = cleaned_crashes.isnull().any().any()
print("Il file contiene valori nulli:", has_nulls)

# Per vedere il conteggio dei null values per colonna
null_counts = cleaned_crashes.isnull().sum()
print("Conteggio dei valori nulli per colonna:\n", null_counts)

Il file contiene valori nulli: True
Conteggio dei valori nulli per colonna:
 RD_NO                               0
CRASH_DATE                          0
POSTED_SPEED_LIMIT                  0
TRAFFIC_CONTROL_DEVICE              0
DEVICE_CONDITION                    0
WEATHER_CONDITION                   0
LIGHTING_CONDITION                  0
FIRST_CRASH_TYPE                    0
TRAFFICWAY_TYPE                     0
ALIGNMENT                           0
ROADWAY_SURFACE_COND                0
ROAD_DEFECT                         0
REPORT_TYPE                      4996
CRASH_TYPE                          0
DATE_POLICE_NOTIFIED                0
PRIM_CONTRIBUTORY_CAUSE             0
SEC_CONTRIBUTORY_CAUSE              0
STREET_NO                           0
STREET_DIRECTION                    2
STREET_NAME                         1
BEAT_OF_OCCURRENCE                  4
NUM_UNITS                           0
MOST_SEVERE_INJURY                  7
INJURIES_TOTAL                      0
INJURIES_FATAL                      0
INJURIES_INCAPACITATING             0
INJURIES_NON_INCAPACITATING         0
INJURIES_REPORTED_NOT_EVIDENT       0
INJURIES_NO_INDICATION              0
INJURIES_UNKNOWN                    0
CRASH_HOUR                          0
CRASH_DAY_OF_WEEK                   0
CRASH_MONTH                         0
LATITUDE                         1022
LONGITUDE                        1022
LOCATION                         1022
dtype: int64